### ISSUE TITLE
The Log in to Get Started button is disabled

### ISSUE THREAD

**Issue by lucksimo** [Esri/ago-assistant#101]
The Log In button is disabled in the Live AGO-Assistant, so how to log in? I am new to this tool, it sounds a great tool, but I just can't find any document to get started.

**Comment by ecaldwell** [comment]
Usually, this happens when a required library fails to load. What browser are you using and what locale/language is your browser set to? Can you open the developer's console and see if any errors show up there?

**Comment by lucksimo** [comment]
Hi Evan,

Thanks for your response.
I am using the latest Chrome (Version 46.0.2490.86 m), and the language is English(Australia)
In the developer's console, there are errors:

GET https://ago-assistant.esri.com/js/lib/arcgis/dojo/cldr/nls/en-gb/gregorian.js 403 (Forbidden)
Error: scriptError(…)
.............(anonymous function)@dojo.js:22

GET https://ago-assistant.esri.com/favicon.ico 403 (Forbidden)

**Comment by lucksimo** [comment]
problem solved. I have to set my browser language from English (Australia) to English (US).

**Comment by garys-esri** [comment]
Same root cause as #95. Interesting.

**Comment by nheminger** [comment]
This locale and the one from #95 appear to perhaps not be listed in the supported locales for the [ESRI Javascript API Localization](https://developers.arcgis.com/javascript/jshelp/localization.html) information.

@ecaldwell, Is this app built using the [ArcGIS API for JavaScript Web Optimizer](https://developers.arcgis.com/javascript/jshelp/inside_web_optimizer.html)? If so, perhaps the dojoConfig just needs updating to add additional locales before another optimized build is run?

As a faster turnaround fail-safe approach, perhaps the dojoConfig should be programmaticaly set to "en-us" whenever a non-identified locale is picked up by the browser? That should perhaps allow the site to at least load in a default of "en-us" and not fail to open for any locales that aren't supported yet.

**Comment by ecaldwell** [comment]
@nheminger Yes, the build is from the JS Web Optimizer. Looking through your PR. Thanks!
