### ISSUE TITLE
App URLs not complete when copied

### ISSUE THREAD

**Issue by oevans** [Esri/ago-assistant#103]
When an item is copied its full URL is not correctly written to the copied item. See below:

![4770643a-9096-11e5-9493-23e849c993b1](https://cloud.githubusercontent.com/assets/3215530/11347797/02a28ec6-91f1-11e5-895f-aabf66b77634.JPG)

@RupertEssinger has noticed that when stories have this issue, like [this one](http://www.arcgis.com/home/item.html?id=8a8745848ed241768bb3ad2ae8d3f7c9) they can't be launched from galleries that are on pages that don't use a valid AGOL domain, like the Story Maps Gallery, Story Maps home page, [Living Atlas gallery](http://doc.arcgis.com/en/living-atlas/#s=0&n=0&d=1&col=&fs=0&fn=30&npp=30&subCat=0&q=GCAMP)
etc.

**Comment by ecaldwell** [comment]
OK, this was actually somewhat of a cheat to make copied story maps work easily. It's actually somewhat difficult to get the org url (e.g. https://myorg.maps.arcgis.com) for a destination account when copying especially when you throw Portal into the mix. I'll have to take another look at this and see what the best approach is for constructing the org/portal url.

**Comment by oevans** [comment]
Can you just default to www.arcgis.com -- that should always work, right?

**Comment by nheminger** [comment]
I may be incorrect, but won't defaulting to www.arcgis.com break any copied apps if the app is being copied to any either Portal instance or to an org on ArcGIS Online?

How would using www.arcgis.com work if the app is copied to a portal? I'm trying to understand how this all would work.

**Comment by ecaldwell** [comment]
It would definitely break it for Portal, but we could handle those a little differently. Using www.arcgis.com might be ok, but I think the better solution is to derive the actual org url and just put that in.

**Comment by nheminger** [comment]
@ecaldwell,

It looks like the ability to derive should be fairly straightforward:

Check if "isPortal":true is found in the "/self" response. If it is, you are dealing with a Portal instance.

1. Portal Instances:
For portal instances, the url will consist of simply the "portalHostname" value from the "/self" response (with protocol prepended based on "httpPort" or "httpsPort" values). This gives you the path to the portal and then you can append the "/apps/[rest of path]" onto it.

2. ArcGIS Online:
For non-portal instances, use the "customBaseUrl" value (i.e. in mine it is "maps.arcgis.com" when I check). Then check "urlKey" value as that is the organization's urlKey. Compose the url as:
"httpsPort"(or "httpPort") + "urlKey" + "customBaseUrl" + "/apps/[rest of path]".

Does that sound correct? Let me know if that approach sounds valid and I'll see if I can work up a fix and create a PR.

**Comment by ecaldwell** [comment]
It does sound correct, but last time I attempted it something wasn't jiving for me. Time to take another swing at it.

**Comment by RupertEssinger** [comment]
This has come up a couple of times recently with users who have used AGOL-Assistant, The resulting item without a domain won't open in http://storymaps.arcgis.com/en/my-stories/ because it tries to adopt the domain of that site

![image](https://cloud.githubusercontent.com/assets/6537271/14400877/903d9c42-fdb4-11e5-9891-845aee8ea863.png)

**Comment by ecaldwell** [comment]
@RupertEssinger I've got a potential fix for this up on the staging site. It should now put the fully qualified org/portal url when copying. Can you run through and see if this resolves the problem?

**Comment by RupertEssinger** [comment]
Hi @ecaldwell Looks good. I did copies inside an Org and between two accounts on the same Org, between Org and Public Account, inside Portal, between Public Account and Portal, and between Org and Portal and always got the correct domain name. 

The only thing unexpected I saw was that for the copy between two accounts on the same Org, it capitalized the first letter in the domain name (see below) but it didn't do that for any of the others.

![image](https://cloud.githubusercontent.com/assets/6537271/14542216/b3243a3a-0242-11e6-9440-41c1c00eb64c.png)

**Comment by ecaldwell** [comment]
Great, thanks for testing all of those scenarios. Not sure about the capital `S`. That's coming directly from `urlKey` in the `portals/self` object so that's how it must be stored there.

I didn't see any problems either so I'll see if I can get this deployed tomorrow. In the meantime, [the change is available on my fork](https://github.com/ecaldwell/ago-assistant/commit/302093a4f754e57b2ddfce7d202bf334c1546ef2) for anybody that wants to see what was modified.

**Comment by ecaldwell** [comment]
Whoops, forgot to close this out when it was fixed in #129.
