### ISSUE TITLE
Update the URLs of Services in a Web Map does not update related tables URLs

### ISSUE THREAD

**Issue by nart-t** [Esri/ago-assistant#106]
Although related tables are part of a base service whose URL you've updated, it doesn't seem to update the relevant JSON section of the web map.

A workaround is to edit the whole JSON of the web map and manually update the related tables URLs separately...but still...they are part of the same service.

**Comment by ecaldwell** [comment]
There are tons of hidden relationships like these between items in a portal. A long term goal for this app is to do a better job of handling situations like you described. It sounds like you were able to successfully edit the JSON directly. Can you share some screenshots or descriptions of the different keys/values in JSON you modified?

**Comment by nart-t** [comment]
Yes...so my goal is to migrate maps/apps between 3 portals (development to staging to production). 

- in this instance I copied a web map from development to staging (via AGO Assistant). One service in the web map was using related tables (non-spatial)
- I went on to update the URLs of the copied web map services on staging, so that they point to the staging ArcGIS Server (exact same services and same folder structure on Server)
- when I checked the web map on staging everything was working fine except I was not seeing related records in the popup
- checked the JSON of the service in question, but this doesn't give any information of the underlying layers/tables
- checked the JSON of the web map and there it was..towards the end of the JSON there is a 'tables' section on the same level with 'operational layers' and 'application properties' of the Data section in the web map JSON. All my related tables were still having URLs pointing to development...after I updated those the related tables showed up in the popup.

<img width="605" alt="screen shot 2015-11-25 at 17 17 05" src="https://cloud.githubusercontent.com/assets/5878887/11404305/187c8da6-9399-11e5-994c-430a457306a9.png">

I found this odd because even the related tables are part of the very same service(s) I updated in the first instance...they still get assigned an id in the service structure (i.e. .../MapServer/'id') as you can see in the screenshot.

Anyways, this is fixable as I said by manually editing the JSON...so in case anyone else stumbles across this...

**Comment by ecaldwell** [comment]
OK great, thanks for detailing your workflow. I just added tables to the "Update Services in a Web Map" dialog yesterday in #105 and I think that may resolve your issue. I haven't pushed the updates to the hosting server yet so let's leave this open until you can test there.

**Comment by ecaldwell** [comment]
I pushed the update (you may need to clear your cache). Give it a shot and let me know if that works better for your workflow.

**Comment by nart-t** [comment]
Fixed! You now get a separate section for tables (if there are any) when you update the URLs for a web map. Thanks and keep it up!

**Comment by ecaldwell** [comment]
Great, glad that worked. Thanks again for detailing your workflow.
