### ISSUE TITLE
Login button does nothing in IE 11 on Windows 8.1

### ISSUE THREAD

**Issue by garys-esri** [Esri/ago-assistant#108]
The login button does nothing in Internet Explorer 11 on Windows 8.1.

When the page first loads, the following error appears in the debugger:

> Object doesn't support property or method 'button'

After that, clicking the `Log in to get started` button does nothing. Instead, it should open the login dialog.

This behavior happens in 7617116a5c50893cb89ac614dc02c55d7eff0509 but not in 8cfe27c4b650511eb98ab5cdd4c8625ff63f1a2e, which means it was likely introduced in 7617116a5c50893cb89ac614dc02c55d7eff0509.

This behavior does not occur in Chrome.

**Comment by ecaldwell** [comment]
Looks like it's a compatibility issue with the [button methods](http://getbootstrap.com/javascript/#buttons-methods) in Bootstrap. I'll have to dig into this one.

**Comment by henry296** [comment]
I have the same issue in IE10.  In the past, launching IE without add-ins solved the issue, but not today.

**Comment by nheminger** [comment]
I think I may have found the issue on this. Going to be hard for me to test it though since I can't reproduce it on my machine (yet). @garys-esri, if I send you changes can you test it on your machine sometime?

**Comment by garys-esri** [comment]
@nheminger, yes, I'll be happy to test. If you put it in a branch, that would be awesome. If that's too much trouble, you can send it to me some other way. Thanks for investigating this issue.

**Comment by nheminger** [comment]
@garys-esri emailed it to you! Hopefully it will resolve. If not, just let me know and I'll continue to investigate.

**Comment by nheminger** [comment]
@garys-esri @henry296 The PR for this fix should be merged in now. Is it fixed for you both now?

**Comment by garys-esri** [comment]
Yes, fixed in c9e0ec038eef76470635d88bcc3ac865d4bfd609 and merged a few days ago. Thanks for the fix!
