### ISSUE TITLE
Full feature service copy creates broken service

### ISSUE THREAD

**Issue by amarinelli** [Esri/ago-assistant#116]
The **Copy Content** feature is still listed as experimental, but wanted to report that despite the Assistant reporting the successful copying of a hosted feature service, the new item does not contain the original data and fails to load properly in the map viewer and is not editable.  I am copying within the same ArcGIS Online account and using the FULL copy type.

When displaying newly copied feature service in map viewer:

![image](https://cloud.githubusercontent.com/assets/4150021/12097637/b1fc3394-b2ea-11e5-8c25-d52160c9f3a1.png)

When attempting to edit in the map viewer (_applyEdits_):

![image](https://cloud.githubusercontent.com/assets/4150021/12097743/64bb260c-b2eb-11e5-9c2b-3634d36cfc72.png)

**Comment by ecaldwell** [comment]
Can you provide some details about the service? What types of features, how many features, how was the original service created, what are its capabilities (create, query, delete), etc?

My guess is that the copy/publishing process is failing and I'm not catching that in the app. Have you tried watching the network traffic and console during the copy process to see if there are any errors there? In the short term, I'd like to add more error handling to detect when it hasn't worked. Longer term, I'm trying to get a handle on why some services copy flawlessly and others fail consistently (hence the experimental label). :smile:

**Comment by amarinelli** [comment]
Not a problem @ecaldwell.  The testing service I am working with was published from the ArcGIS Desktop tutorial data (Zion National Park).  There are several layers in the feature service, each with a small amount of spatial/attribute data.  The service is currently shared with *Everyone* and can be found [here](http://www.arcgis.com/home/item.html?id=8d4ea6fd60564f23af785a1534144a84).

The layer definitions are relatively complicated with a number of different types/templates.  The original service was published with the basic *Create*, *Delete*, *Query*, *Update* capabilities but does not use *Sync*.

Viewing the network traffic during the copy operations does not show any obvious errors.  The *createService*, *update*, and *addToDefinition* operations all are successful.  It is not until the *addFeatures* operation that every record inserted fails with the following error:

![image](https://cloud.githubusercontent.com/assets/4150021/12122552/c6cfad40-b3a9-11e5-8dce-a52539f6bf2b.png).

Let me know if there is any additional information I can provide.  I am going to republish the service from source data and see if anything changes when attempting a full copy.

**Comment by ecaldwell** [comment]
Thanks for the detail @amarinelli. I need to go back and look at my error handling for the `addFeatures` step. Maybe a good interim solution is to do a final check of the `recordCount` on each service and if they don't match present some additional info.

**Comment by ecaldwell** [comment]
Fixed in #160.
