### ISSUE TITLE
Selecting "View My Stats" has errors

### ISSUE THREAD

**Issue by nheminger** [Esri/ago-assistant#117]
Periodically selecting "View My Stats" opens a modal but produces the following javascript errors in the browser console:

![image](https://cloud.githubusercontent.com/assets/5648650/12205298/ccdf4a78-b607-11e5-8226-9b0abe68b7cd.png)

After closing the modal, clicking "View My Stats" a second time produces the following error and does not pop up any modal:

![image](https://cloud.githubusercontent.com/assets/5648650/12205321/ebbc0544-b607-11e5-9254-36aa0bc10ed9.png)

This is exhibited on https://ago-assistant.esri.com/ in Chrome version 47.0.2526.106 m. It does not always manifest and may be due to a timing issue. It appears to happen more often when opened in an incognito tab.

**Comment by ecaldwell** [comment]
Thanks for logging this. I have noticed this before, but inconsistently. I'm fairly positive it's an issue with the cal-heatmap library not loading properly. I haven't been able to find any good reason that library goes unrecognized, since it loads with everything else when the app is launched.

**Comment by nheminger** [comment]
Appears it could me something to do with AMD versus non-AMD libraries trying to load at runtime (cal-heatmap and/or d3?). @ecaldwell does that sound like a potential cause?

**Comment by ecaldwell** [comment]
> ...does that sound like a potential cause?

It does. I experimented with trying to lazy load the library, but that didn't improve it. I'm not sure why this particular library fails to load sometimes.

**Comment by ecaldwell** [comment]
@nheminger Maybe we could try [calendar-heatmap](https://github.com/DKirwan/calendar-heatmap) instead and see if it behaves a little more consistently.

**Comment by nheminger** [comment]
@ecaldwell Wow, good find. That makes sense.

Do you foresee any potential trade-offs between it and the current cal-heatmap that I should try to evaluate if I get time to swap it in? Or do you think they are pretty much exchangeable as far as functionality/trade-offs and if it works just try to use it?

**Comment by ecaldwell** [comment]
It provides pretty much the same view as the existing implementation so the only real implications to me would be how it affects the overall application. 

It adds an additional dependency (moment.js) so that potentially increases the overall application size. This might be a moot point if I ever get around to optimizing the build with a bundler like webpack or rollup. 

I think it's worth a shot on a dev branch to experiment with.

**Comment by ecaldwell** [comment]
Closing this since I pulled the troublesome library out in #168.
