### ISSUE TITLE
Content server link

### ISSUE THREAD

**Issue by henry296** [Esri/ago-assistant#118]
I have been using ArcGIS Online Assistant to manage switching my web maps between different environments (DEV, QA, Production).  I noticed today in one of those maps, that if I look at the web map properties in ArcGIS Online it shows the correct server.  But when I open the web map and click the Show Item Details it takes me to the REST endpoint on a different installation of ArcGIS server.

I've been looking into why changing the symbology in my services is not being reflected in my web map unless I add the content again.

Thanks.

**Comment by nheminger** [comment]
@henry296 Is it the "(Link to Item Details)" at the top of the page you are referring to when you wrote that it takes you to a REST endpoint on a different installation of ArcGIS server? Is this happening with a web map you have not copied or is it only showing up after you copy it to a different portal instance?

**Comment by henry296** [comment]
I’m clicking on the Item details via the layer menu in the Web Map.  It is taking me to a different REST endpoint on a different server installation than what shows up in the web map properties.    All of my web maps are on the same organization ArcGIS account.  I’m not using Portal.  I did copy the web map to a different folder using ArcGIS Online Assistant and then updated the service URLs.


[cid:image001.jpg@01CEB48E.2B0533C0]<http://www.dickssportinggoods.com/home/index.jsp>

Todd Henry
Sr Technical Manager, Real Estate Market Research
345 Court Street  l  Coraopolis, PA  15108
todd.henry@dcsg.com<mailto:todd.henry@dcsg.com>  l  o: 724.273.4026  l  m: 412.522.3269

[cid:image002.png@01CEB48E.2B0533C0]<http://www.facebook.com/dickssportinggoods>[cid:image003.jpg@01CEB48E.2B0533C0]<https://twitter.com/DICKS>

**Comment by nheminger** [comment]
@henry296 Okay, so is the problem occurring when you open the webmap in the ArcGIS Online web map viewer, click the "Details" button/section and then click the "More Details..." and that pops open a new tab but the url at the top of the page is not the correct one? Can you attach screenshots of where you are clicking and what the problem looks like with the urls?

**Comment by henry296** [comment]
This definitely sounds similar to #52 where the item details is linked to the old ArcGIS ItemID, but the map still points to the changed service URL.  Attached are the screenshots of the process I followed.


[cid:image001.jpg@01CEB48E.2B0533C0]<http://www.dickssportinggoods.com/home/index.jsp>

Todd Henry
Sr Technical Manager, Real Estate Market Research
345 Court Street  l  Coraopolis, PA  15108
todd.henry@dcsg.com<mailto:todd.henry@dcsg.com>  l  o: 724.273.4026  l  m: 412.522.3269

[cid:image002.png@01CEB48E.2B0533C0]<http://www.facebook.com/dickssportinggoods>[cid:image003.jpg@01CEB48E.2B0533C0]<https://twitter.com/DICKS>

**Comment by henry296** [comment]
I wanted to provide a little bit of detail on how this is impacting me specifically when I change the underlying service on ArcGIS server.

Below is a test I ran by updating the service URL of an item that I added from My Content and changed the URL vs. one added directly from the service URL.  It seems like with this issue, I should be building my web maps by adding content from the web instead of searching for layers in MyContent.



1.  The first was created using Add Layer from Content using one server location and then using ArcGIS Online Assistant to change the service URL.

2.   Adding a second layer to the web map directly from the web using the server URL, so that both layers have the same URL in the web map properties.

3.  Changed the color the symbology for the service URL from a green star to red star.

4.  The first layer that was originally added from My Content did not reflect the new symbology, but the 2nd layer did.

5.  I edited the data in ArcMap and both layers showed the updated data so that it is pulling from the same database and service URL.





[cid:image001.jpg@01CEB48E.2B0533C0]<http://www.dickssportinggoods.com/home/index.jsp>

Todd Henry
Sr Technical Manager, Real Estate Market Research
345 Court Street  l  Coraopolis, PA  15108
todd.henry@dcsg.com<mailto:todd.henry@dcsg.com>  l  o: 724.273.4026  l  m: 412.522.3269

[cid:image002.png@01CEB48E.2B0533C0]<http://www.facebook.com/dickssportinggoods>[cid:image003.jpg@01CEB48E.2B0533C0]<https://twitter.com/DICKS>

**Comment by henry296** [comment]
Here is some more information.

Even for the services that were previously added using the URL, I’m seeing this issue.

Here were those steps.


1.        Build web map by adding content using ARcGIS server REST endpoint URL.

2.       Update URL using ArcGIS Online Assistant.

3.       Change symbology in ArcMap and republish the update service.

4.       Symbology does not change in the updated web map because the symbology is imbedded in the JSON.


[cid:image001.jpg@01CEB48E.2B0533C0]<http://www.dickssportinggoods.com/home/index.jsp>

Todd Henry
Sr Technical Manager, Real Estate Market Research
345 Court Street  l  Coraopolis, PA  15108
todd.henry@dcsg.com<mailto:todd.henry@dcsg.com>  l  o: 724.273.4026  l  m: 412.522.3269

[cid:image002.png@01CEB48E.2B0533C0]<http://www.facebook.com/dickssportinggoods>[cid:image003.jpg@01CEB48E.2B0533C0]<https://twitter.com/DICKS>



From: Henry, Todd
Sent: Thursday, January 28, 2016 9:05 AM
To: 'Esri/ago-assistant'; Esri/ago-assistant
Subject: RE: [ago-assistant] Content server link (#118)

I wanted to provide a little bit of detail on how this is impacting me specifically when I change the underlying service on ArcGIS server.

Below is a test I ran by updating the service URL of an item that I added from My Content and changed the URL vs. one added directly from the service URL.  It seems like with this issue, I should be building my web maps by adding content from the web instead of searching for layers in MyContent.



1.  The first was created using Add Layer from Content using one server location and then using ArcGIS Online Assistant to change the service URL.

2.   Adding a second layer to the web map directly from the web using the server URL, so that both layers have the same URL in the web map properties.

3.  Changed the color the symbology for the service URL from a green star to red star.

4.  The first layer that was originally added from My Content did not reflect the new symbology, but the 2nd layer did.

5.  I edited the data in ArcMap and both layers showed the updated data so that it is pulling from the same database and service URL.





[cid:image001.jpg@01CEB48E.2B0533C0]<http://www.dickssportinggoods.com/home/index.jsp>

Todd Henry
Sr Technical Manager, Real Estate Market Research
345 Court Street  l  Coraopolis, PA  15108
todd.henry@dcsg.com<mailto:todd.henry@dcsg.com>  l  o: 724.273.4026  l  m: 412.522.3269

[cid:image002.png@01CEB48E.2B0533C0]<http://www.facebook.com/dickssportinggoods>[cid:image003.jpg@01CEB48E.2B0533C0]<https://twitter.com/DICKS>

**Comment by slibby** [comment]
These are underlying Online issues and Web Map Issues, nothing specific to Assistant.
