### ISSUE TITLE
Cannot edit JSON for story map

### ISSUE THREAD

**Issue by upcamogie** [Esri/ago-assistant#119]
I am trying to change the title of my story map because it is not updating with the new name when I use a twitter link. I click on the edit link (pencil) and assume the risks of editing. However, when I try and change anything, the cursor will not appear in edit mode. If I press delete or backspace, my web page goes back-- its like the editing function is disabled. Editing the json was a suggestion from a story maps developer to change the app title since there is a bug preventing the title from updating automatically.

I tried the AGO assistant in Chrome and Firefox, same result. I have successfully edited json in the past so this seems like a recent problem.

**Comment by ecaldwell** [comment]
Couple of basic troubleshooting steps. First, confirm you own the item (or have admin rights in the org that owns it). Second, can you edit any other items? Is the edit experience broken for everything or just this one item in particular?

**Comment by upcamogie** [comment]
I am the owner and I have the admin rights. I can edit other items (web maps) but it seems that apps are not editable--story maps or web app builder (the only 2 that I tried)

**Comment by ecaldwell** [comment]
Just curious, how did you create the app? Which property specifically are you trying to update? Is it `title`?

**Comment by upcamogie** [comment]
Yes, I am trying to update the title property so when I share my app via the social media links (specifically Twitter I am testing), it shows the correct name and not 'test.'

I created my app on ArcGIS online and then use that appid in a hosted story map journal template. I do not have all the source code and only host the app so i can have a nice URL for my app.

I was told by support that they do not support the AGO assistant- not happy about that fact as that was my next move as I need to share this app in 2 days and would like the links to be accurate

**Comment by upcamogie** [comment]
update- I can edit the 'description' items of the JSON but not the 'data' sections. So I can change the title in one place but not the other....and the app links use the title from the 'wrong' place.

**Comment by ecaldwell** [comment]
OK, just want to make sure I understand everything here about your scenario. Do I have this right?
  1. You created a web map in ArcGIS Online.
  2. You created a web app from the web map in step 1 (using a pre-built template) and host that in ArcGIS Online. 
  3. You have the Story Map Journal running on your own web server and one of the pages it loads is the hosted app from step 2.
  4. The title displayed for the app (from step 2) is wrong when viewed in the Story Map Journal.

**Comment by ecaldwell** [comment]
>  I do not have all the source code and only host the app so i can have a nice URL for my app.
Can you clarify this line for me?

**Comment by upcamogie** [comment]
I got it work! Silly user error on picking the right edit tools....I think we can close this because when using the right edit tool. thanks and sorry for the unnecessary post at this point!

**Comment by ecaldwell** [comment]
:+1:

**Comment by upcamogie** [comment]
im doing too much at once with this app, the non developer in me = overwhelmed! thanks again
