### ISSUE TITLE
Implement Group Membership copier

### ISSUE THREAD

**Issue by oevans** [Esri/ago-assistant#12]
Currently there is no way through the UI for administrators (or anyone) to see a list of groups that another user is a member of (not an owner of).

Implement a tool to get a list of group membership from one account and transfer membership of all or a selection of groups to a target account.

**Comment by slibby** [comment]
Going forward, AGO-Assistant will be designed and updated to primarily focus on item-level workflows, not topics like sharing and groups, this is better served through a simple Python Notebook with the ArcGIS Python API.
