### ISSUE TITLE
Updating URLs from secure to 'normal' for AGO content items

### ISSUE THREAD

**Issue by upcamogie** [Esri/ago-assistant#120]
I initially created AGO content items using the option to 'save credentials' and now I want to update to use the regular map service URL since I have removed the security on the server folder. I can change URLs for map image layers that do not have the 'utliity.arcgis.com' service URL jsut fine. But when I change the secure URL, it appears to work but then it defers back to the secure URL. I am trying to avoid creating all of the metadata again for my layers. I can update other things like the name of the layer, just not a URL that was once secure but now is not.  ideas?

**Comment by nheminger** [comment]
@upcamogie What type of workflow are you using when doing this update? Are you selecting the "View an Item's JSON" and then editing the JSON from there?

Is this an item you have on ArcGIS Online? Can you create a separate test example and share that for me to investigate it?

**Comment by upcamogie** [comment]
@nheminger- For the actual map image layers (content), I tried the 'update the URLs of registered apps and services' and selected my content item. The URL does indeed change with the 'success' but if I log out and back in, my original, secure URL persists. 

I also tried the 'view an items JSON' and changed the 'url' to match the 'sourceurl' and again, it changes and I get the 'success' message. But when I log out and in, same thing, the old URL is there. 

To test, I can share my service back out to ArcGIS Online so you can see it [here](http://mwcog.maps.arcgis.com/home/item.html?id=fc36e63d4cf54450a2cfba4a160c18b4) is that enough? or do i need to provide you credentials

**Comment by slibby** [comment]
@upcamogie a service item with embedded credentials is different than a simple registered service, it will not let you change the source URL as it is 'baked in' to the AGO utility proxy that provides the credential embed. What I would recommend is using AGO-assistant and the "Copy Items" tool to copy your original item, which will preserve all your metadata, field settings, popups, etc, but will create a new 'simple' URL-based item which will then let you edit the URL.

**Comment by ecaldwell** [comment]
@slibby :+1:

**Comment by upcamogie** [comment]
@slibby I believe that was my first line to try but I recall not being able to replace the secure URL in the copied content. This is why I was exploring different ways to update the URL. I will have to go back and try again but I am almost certain this was a limitation to me.

**Comment by slibby** [comment]
@upcamogie just tried it on an image service and seemed to work fine to update it through the AGO UI.

**Comment by upcamogie** [comment]
Thanks @slibby  I will try it again :)
