### ISSUE TITLE
Partial String Search

### ISSUE THREAD

**Issue by DShokes** [Esri/ago-assistant#123]
I've come across some odd behavior when searching for items:

* Searching "Jobsite" returns these item names:
  * "Ohio Jobsites", "Australia Sites", "ManagementTemplate" and many others
  * The items without "Jobsite" in the name have "Jobsites" in the snippet or description 
parameters
  * No items contain the singular word "Jobsite"
  * The same behavior is seen searching "Tree" and getting items containing "Trees"
* Searching "Austral" return 0 results
  * The item named "Australia Sites" has the word "Australia" in both the snippet and description.
  * Why isn't "Australia Sites" in the results?

Perhaps this is some limitation or an  [undocumented](http://doc.arcgis.com/en/arcgis-online/reference/search.htm) attempt to handle plurality by the AGOL search engine?

**Comment by ecaldwell** [comment]
The search is nuanced for sure. A standard keyword search is going to return a lot of results where that keyword pops up in the snippet, decription, etc (as evidenced in your "jobsite" example). 

Have you tried adding a wildcard to your second search? Try `Austral*` and see if you get the expected items back. You can also use `title:Jobsite` to further constrain your first example to items where that word has to occur in the title.

**Comment by DShokes** [comment]
Thanks, I had only tried % previously! 
* ```Austral*``` works as expect. However, 
* ```*ustralia``` returns every item in My Content. 
* ```title:Jobsite```, ```title:Jobsite_``` and ```title:Jobsite ``` (space at the end) return the same results which include: "Georgia Jobsites", "Jobsites_Backup"
* ```title:Saluting Branches``` returns 22 items including "Saluting Branches" and "Saluting Branches Web Map", but not "SalutingBranches2"
* ```title:Saluting Branches*``` returns 0 items; not "Saluting Branches Web Map" as expected
* ```title:Saluting*Branches``` returns 0 items; expected "SalutingBranches2" and "Saluting Branches"
* ```title:Saluting_*``` returns 0 items even though ```title:Saluting_``` returns 15 results```
* ```title:Saluting*Branches*``` returns 4 different items including "SalutingBranches2" and "SalutingBranchesSiteNotes"

As a note, trying this on the AGOL search returned an error "Wildcards not allowed."
Is ```*``` the only wildcard? Is there syntax for begins or ends with character? Is there a way to search 0+ spaces, so that "Saluting Branches" and "SalutingBranches" would both appear in the results? 

Thanks

**Comment by ecaldwell** [comment]
The [REST API Search Reference](http://resources.arcgis.com/en/help/arcgis-rest-api/index.html#/Search_reference/02r3000000mn000000/) has some additional info and examples. Use `?` for a single character wildcard and `*` for multiple characters.

This app is just using the API directly so you might want to report any inconsistencies with the results through geonet or Esri tech support.

**Comment by nheminger** [comment]
@ecaldwell @DShokes Before reporting... I am working on some notes as some of the behavior described is expected. I will try to respond with those notes shortly to hopefully assist in any further debugging.

**Comment by DShokes** [comment]
Thanks for the quick responses and the API link. This helped:

> +
> The "+", or the required operator, requires that the term after the "+" symbol exist somewhere in the given field or the default fields.
> To search for items that must contain "fires" and may contain "recent", use the following query:
> ```
> {
>   recent +fires 
> }
> ```

I'd never seen ```+``` used to operate like that before, but it works: ```+Saluting``` returns both "Saluting Branches" and "SalutingBranches". 

However, I'm still confused why:
  * ```Jobsites``` and ```+Jobsit*``` return the same 33 results
  * But  ```+Jobsite*``` and  ```+Jobsites*``` only return 1 result; "Jobsites_Backup" 
  * And  ```+Jobsite?``` and  ```+Jobsites?``` return 0 results
    * There appears to be no wildcard for spaces or underscores
  * Searches with "_" return strange results

**Comment by nheminger** [comment]
@DShokes 

For the search `*ustralia`:
I believe the search does not support wildcards at the beginning of the field like that. So I believe it is interpreting that search either as simply `*` and then returning all results, or it is searching across all metadata fields for `ustralia` and returning a lot based on that.

According to [http://resources.arcgis.com/en/help/arcgis-rest-api/index.html#/Search_reference/02r3000000mn000000/](REST API Search Reference), 

> Single and multiple character wildcard searches within single terms (not within phrase queries) are supported.

This means that the wildcards can only be applied to single terms and not phrases or groups of words. I believe you may be seeing inconsistent results because `+Jobsite*` may be trying to both do a wildcard search but also make that term required. I haven't narrowed down where in the documentation that might be addressed, but it appears unlikely that would work.

For these inconsistent results, can you describe further what results you are looking for that are not getting returned?

**Comment by DShokes** [comment]
@nheminger , 
I created some testing web apps with the following titles:
"Jobsite1", "JobsiteTest", "test jobsites1", "Test Jobsite 1", "Test_Jobsites_1", "TestJobsitesTest", "TestJobsiteTest"
* I searched for ```title:Jobsite``` but "JobsiteTest", "TestJobsitesTest", and "TestJobsiteTest" were missing.
* Then I tried ```title:Jobsite*``` and this time "Jobsites1", "Test Jobsite 1", "Test_Jobsites_1", "TestJobsitesTest", and "TestJobsiteTest" were all missing.
* When I tried ```title:Jobsite?```, only "Jobsite1" was returned.
* Last I tried ```title:+Jobsite``` and ```title:+Jobsite*``` both returned 0 results. 

The goal is to search for every item containing the string "Jobsite" somewhere in the title. It doesn't seem doable.

**Comment by nheminger** [comment]
@DShokes ,

That is strange. Unfortunately the limiting factor is needing to have a leading wildcard character, which isn't supported. In other words, knowing that there is a "jobsite" later in the string doesn't help cases where it starts with that. If you knew that, then the following search returns all 7 of your results:

`(title:Jobsite OR title:Jobsite* OR testJobsite*)`

I know that tags are recommend as a way to go with categorizing items. For whatever workflow you are using can you tag all items with "jobsite" and simply search for everything with that tag?

**Comment by ecaldwell** [comment]
Lots of good info in this thread. Are there any additional questions on this topic to be discussed or should I close this one out?

**Comment by DShokes** [comment]
Thanks for the feedback @nheminger. Looks like I'll just have to make sure users (and myself) follow some naming best practices.
