### ISSUE TITLE
AGO Assistant hosted site certificate expired

### ISSUE THREAD

**Issue by nheminger** [Esri/ago-assistant#127]
I noticed the site at https://ago-assistant.esri.com/ has an expired certificate:

![image](https://cloud.githubusercontent.com/assets/5648650/14359082/e6bb0714-fcbd-11e5-9630-b5f1982c308f.png)

When I went to the site recently I got prompted on whether I should trust the "invalid" cert or not. Trusting it did allow me to login and use the site, but it may be good to update it so the security warning doesn't scare users from using the site.

**Comment by ecaldwell** [comment]
Uh oh, that's not good. I updated (or attempted to) the cert a few weeks ago. Let me dig in and see why it didn't take.

**Comment by ecaldwell** [comment]
Fixed. Thanks to @CraigCleveland for showing me what I was doing wrong with the AWS Cloudfront certificate upload process.
