### ISSUE TITLE
"copy" does not actually copy data, only creates a link to original data

### ISSUE THREAD

**Issue by CodyBenkelman** [Esri/ago-assistant#134]
I published imagery for the **World Wildlife Fund** using my own AGOL account, then used ago-assistant to copy from my account to their account.  We published the imagery from their account and it worked fine, but when I deleted what I believed to be the original _copy_ from my account, the imagery was lost from their account.  

Having an option to create a link would also be useful, but the "copy" command needs to actually make a copy, not a link!

**Comment by ecaldwell** [comment]
What was the item type for the content that you copied? There is an option to "Full Copy" a hosted service. That process creates a full replica of the original service complete with data in the destination account. The Simple Copy option creates a reference (link) to the original.

**Comment by CodyBenkelman** [comment]
Evan
This has been a couple of weeks, and I have to be honest that I don’t recall what I did.

I looked at the assistant UI again today, and I am sure I hit “copy” but I don’t understand why some items are not selectable – I am guessing now that what I must have done was copy an *image*service* (or maybe a web map), but did not realize I did not select the source imagery for that service.  If correct, in this case it makes sense that a service points to the original data and did not copy the source data.

However I can’t see the “Full Copy” option you’re referring to – this is all I see:
[cid:image002.jpg@01D1B11C.4F1A2850]

Should there be a follow-on confirmation menu after a copy, “execute Simple Copy or Full Copy?”…?   I don’t see many features so don’t understand how to invoke a Full Copy.  I’m on Chrome – should I be using a different browser?

Cody

**Comment by ecaldwell** [comment]
The full copy option only appears for Hosted Feature Services. If you were copying an image service, then all it was doing is cloning the ArcGIS Online item, which itself was just a bookmark to the image service which lived on an instance of ArcGIS for Server somewhere. [Here is an example](http://www.arcgis.com/home/item.html?id=161bcbbee9a94c0a992c5bd5428b13dd). Copying that item will register the service in your own organization, but the image service itself still lives at http://imagery.arcgisonline.com/ArcGIS/rest/services/LandsatGLS/FalseColor/ImageServer.

Is there anything that could be done differently in the UI that would have helped you better understand what the copy option was doing?

**Comment by CodyBenkelman** [comment]
Evan

Thanks for the info.  I’ve tested more and it appears that in any case where the item is a data file, it is white and can’t be selected for copy – so I should have known what I was attempting (move hosted data) was not possible – but this does make me ask why that can’t be done (or perhaps “when?”) because I think users will want it (as I did).  Since we charge people for hosting data, I’m sure there will be cases where users want to transfer data between accounts.

Other than that, I’d suggest

A)     Some kind of help or guide for why some items are white and can’t be selected,

B)     And perhaps a confirmation message for any copy stating what will be copied (along the lines of what you wrote below).

If I think of other suggestions I’ll write again

Thx
Cody B.

**Comment by ecaldwell** [comment]
There is a lot of work to be done in intuitively explaining why some actions can't be worked with. Specifically, files aren't supported yet because they require a proxy to transfer the files between accounts and one of the goals is to keep this app 100% client side so that it can be easily deployed on networks.

I'm trying to plan out some moderate UI changes and I'll try to incorporate this as best I can. One thought is to have a "mode" selection for the type of copy: Copy a reference to the original vs Replicate this in my account. 

This is great feedback. Keep it coming! 👍

**Comment by CodyBenkelman** [comment]
Thanks Evan
I hope it’s helpful
Thanks for your feedback
Cody B

**Comment by slibby** [comment]
@CodyBenkelman are you ok with closing this issue?

**Comment by CodyBenkelman** [comment]
Yes, this can be closed
Thanks
Cody B
