### ISSUE TITLE
Update URL\Renderer Issue

### ISSUE THREAD

**Issue by kevinsigwart** [Esri/ago-assistant#135]
There seems to be an issue when updating the URL of a service when the Portals are different, where the renderer is still referencing the old Portal for all symbols.

Workflow:
Copy Web Map from One Portal to Another Portal
Update URL to point to service in new portal
Check the JSON, and see that the renderer is still referencing icons in the old Portal

**Comment by ecaldwell** [comment]
> ...still referencing icons in the old Portal

What do the references look like? Are they simply urls to assets in that portal? This is a tricky one. We could swizzle the urls to point at the destination portal, but if they're not default assets then you'll just have broken links.

**Comment by ecaldwell** [comment]
Can you share a screenshot or sample json of the references?

**Comment by kevinsigwart** [comment]
`    {
      "id": "Site_Points_Extended_Attributes_7872",
      "layerType": "ArcGISFeatureLayer",
      "url": "https://<serverurl>/server/rest/services/VA/Site_Points_Extended_Attributes/MapServer/0",
      "visibility": false,
      "opacity": 1,
      "mode": 1,
      "title": "VHA Sites",
      "itemId": "faee03bd20654b0dab33d905b3972bca",
      "layerDefinition": {
        "definitionExpression": "(accountableOrganizationCode = 'VHA') AND (operationalStatus <> 'VAMC')",
        "drawingInfo": {
          "renderer": {
            "type": "simple",
            "symbol": {
              "angle": 0,
              "xoffset": 0,
              "yoffset": 0,
              "type": "esriPMS",
              "url": "http://<serverurl>/portal/portalimages/Symbols/OCHA/Infrastructure/infrastructure_house_bluebox.png",
              "imageData": "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAZcSURBVHhe7ZvdTxxVGMYHiNa0lUIbr1pLNcYbL/0H9NbEeKP3GtDa8lESS1EvNNE7vWn8A3pnNcZoSoE1BWNMtMUbsVbbGG1TvgqxgNCysGx3Z3x/Z+Zsz24OO7uz38CbPOxh5sw5z/Ocz5nMOJ7nZSHtus3y20R6cW3T+Xxi5pXXz01++NwHP0y0do94bT2j7oGeUa8eATc4whXOcEdDoK0p0JalN+sfnSGRTDtnx26++vxHP/70yFsXPbD/5Ii10noEXDVvNKAFTaZGjUwilXZb+L0xf//JFz75+Runc8jbc3zYO9gXc9v7Yql6bvlcwBXOcEcDWtCENlMrUH+0K9dmV488+/73ky1dQ96hU7F0e28sZaugkYAGtKAJbWg0NWfG/F8La4i/imOH+mJJW2GNDDShDY1oRTPaxQCvOZ5INb346eVvVcv3fffAVsB2ANrQiFY0o10Ngc/Gb73mdF7ApYbv8mFAI1rRrIbA4v3NR2WmvCzdI83EYbtoOwGNaEUz2p3zE7Mvy3KRkBkT8Q0z05cAF61oRrvzxrnJj1kv5WDVx77M0Aq2c5UEWtGMdkd2TVfYOFR7nW8T4dIVHwDStjyVAlrRjHantdueqVJQm5TeUTYnm6e/+nMGkOZYtRsB7Y4kqlYpAg9Kazd3DSVPfXFtVmbhTUCaY5yrsgkuBthOVATtfaNeU9eQEizCE7IR8QBpjnGOPLZrK4WqGNDW67e8CEz2B+LRbYJjnCOP6glyja2scqMqBsja6zXJOKeVXdfdpNXlV6kmSAfHVB7yco2trHKjogaYLa+7PbIN7ZngWHBYD4eq9ISKGhC0vIj/Y1ZaOCG3oVktnxucIw95uYZrK90TKmKAWupyJjyjhfMGeQKPsibGSq0OlTCAraZa6vq/lDEvQhjfoNDQ+bmWMtQS6feEsptQVgOklTJLXZ/Z8oVrz4RxXYKyjJ5grTsqymYAXTR3qZPhHEm8Dq6lDInsJbKMPaFsBuhuz7iVyUx1+1LE6/BNUJOnmhOM4VAWlGyAWuoQr2b7/Etd1KCsoDjfBKmLOsuxRJZsALez0ipqtpeWClq+jOqDoEzKpo6gJ8gNVOk9IbIBasxLKzA5ZVr+YUtVJCg78DazRKqeUMKcENkA1e0Z87JMyUQVuskpV1CHv1kSE7KXyEgo2gDc5t6d/XrWUufzq0qYPUEtkSU8TyjKANXt/THvz/ZCwB/zikxVgzpV3cFwUD0hwhJZlAHm9paKIVEL8Tp0/XDRcwIcbdy3QkEGmHd1uffztQ6DR6TnCQUZEHY/X+vQSyTcVE8o4nlCqAFtPTHP6byQ6Dn/+4zUtcEMLKgf9UHACW4SG3CFM9xtmkzkNYDH1Y+9PZwa/Pr6v1Jw3YnOEy6c4R72yH1LA2RZcfccv+i9dHbi7+tz9278Nr06Jbh9dUYgv8lUOhVUVvOAC5zgBke4whnuaECLTSPI2wMe7x7xjg2OxY8OXFo6/M6lpSOnfRwWLNxLpKm8loNB1w0XOGX4CVc4wx0NNm0aoXPAvhMj3r6TI+q1Ew3+n19NqMrrwQC42DjC3abJRAGToL8MmjggqDcD4JTLE+42TSZCDbChVVCKAVxjQ7Ghr4ELnGxcw1ATA8oVDWmALNfuSjyZXo4nPRMc41yQraBoKAP03ml6aX31mffGF7h7e6I/5gLSHOOcmTcsGtKAKRHZMTC2sFdmaCnHBaQ5xjkzb1g0rAHHzowtsFTp2Zo0x3YN2DVg14BdA8y8YbFrwK4B/m9NDLizkmDf5qbTwsN/QpYXPLHh9/bi+spWBnDOzBsGXTdcSjGg6GfpVHZ3jTfcio+5lY21rQzgXJCtqIBLRAPcyC9K/jq1unBnZWN2emljbnY5HLLNnZtfScz9cuu/m0cHxu7u5/sjbYCkOcY58pDXVkYuqBsOcLFxDIN6UTLqq7IdZ8bWn353fO2pwfF4oZD8cbkuLqLTueVxjHPksV27FeAAl9zy8gGtaFavykZ9WZqnLXtPDAv4LQTkHc77lOZhmcWVW8iTHxNozbwsHfV1eWmxyLCVB2x5C4WtvC2Q/br8jv9gQibRnf3JTHqnfzQle46d/dkc3SAwwbnyz3IHHxe2vLkNP5wUTWhDo6lZGQBk+7lzP53VSAWubOePp7VGjUxCQ88JpLf/5/Oe8z+pI0mgjbE9cwAAAABJRU5ErkJggg==",
              "contentType": "image/png",
              "width": 11.25,
              "height": 11.25
            }
          }
        }
      },`

**Comment by kevinsigwart** [comment]
The renderer is a simple marker symbol with a url like..
"http://<serverurl>/portal/portalimages/Symbols/OCHA/Infrastructure/infrastructure_house_bluebox.png"

**Comment by GISDev01** [comment]
This would probably require the code to check if that png exists on the new portal URL before changing them all transparently. I'd guess some people could pop some custom icons in that directory in their On-Prem Portal deployment. The issue with checking the existence of the png's on-the-fly is if the user doing the copying doesn't have proper connectivity or access to see those png's, possibly?

**Comment by ecaldwell** [comment]
This seems semi-complex to address. One option is to globally update the portal url references, but that won't help if those symbols don't exist in the new portal. There is definitely some work to be done with updating the other components of the item. For example, there is an `itemId` property which is also portal specific. That definitely needs to be updated (or removed).

I think I'm going to label this one as `won't fix` and address the `itemId` update in #52.

**Comment by ecaldwell** [comment]
I added a new `coding challenge` label for any ambitious souls out there who want to take this one on.

**Comment by slibby** [comment]
No longer relevant - issues with copying to other portals + item ID handling are tracked in #52
