### ISSUE TITLE
Any type of web map/service that does not respond to URL updating?

### ISSUE THREAD

**Issue by upcamogie** [Esri/ago-assistant#136]
I made a typo when I updated my URLs in a web map to go from http to https and now I cannot fix it-- the nice 'success' message I usually get upon updating URLs does not happen and my URL reverts back to the incorrect one. Other web maps work as expected, but neither this original web map nor the copied version I have in another folder allows any further modifications to the URL. 
Any ideas? thanks

**Comment by ecaldwell** [comment]
Can you update any other parts of the url like appending `/abc`? or do those updates fail as well? Any messages in the developer console?

**Comment by upcamogie** [comment]
@ecaldwell 
in the main 'console' tab there is an error "uncaught typeerror: cannot read property '1' of null

There is no other action in the developer console that  I can see- not sure where to look really though. But  I do see on the network tab when I update other datasets and click 'update' there is some get/post lines but with this one web map there is nothing listed.

**Comment by GISDev01** [comment]
Can you paste the whole error you're seeing in the console, along with the "uncaught typeerror: cannot read property '1' of null".
Usually, it will have a line number and filename (e.g. index.js:11, meaning the error occurred on line 11 of the file called index.js) on the far right of the console when an error like that shows up. I assume you're using Chrome?

**Comment by upcamogie** [comment]
@GISDev01  here is the only info that appears in the console with that error- hopefully this helps

Uncaught TypeError: Cannot read property '1' of nulli @ main.js:2(anonymous function) @ main.js:2each @ jquery-1.10.2.min.js:4(anonymous function) @ main.js:2c @ jquery-1.10.2.min.js:4fireWith @ jquery-1.10.2.min.js:4k @ jquery-1.10.2.min.js:6r @ jquery-1.10.2.min.js:6

**Comment by ecaldwell** [comment]
@upcamogie Can you share the map with me? Have you tried editing the JSON directly to see if you can fix it there?

**Comment by upcamogie** [comment]
@ecaldwell I was able to change it via JSON, I forgot to try that before (thanks)

My web map is here http://mwcog.maps.arcgis.com/home/item.html?id=c259cb6344194b799f2327b37abc8664
changed it be shared so you can see it. the layer that had the typo was the 
https://gis.mwcog.org/wa/rest/services/RTDC/ActivityCenters_TAZ/MapServer

**Comment by ecaldwell** [comment]
@upcamogie Do you know what the typo was? I'm guessing something that resulted in malformed JSON. The json editor actually does some validation to prevent issues like this so I'm wondering if validating the url would have prevented this problem.

**Comment by upcamogie** [comment]
@ecaldwell the typo was in the https part-- I typed 'httsp' when adding the 's' to my service URLs as part of our fixing our maps/apps to display either via http or https. 
It sounds like validating the URL may have prevented it since httsp goes nowhere...hope this helps

**Comment by ecaldwell** [comment]
I add issue #139 to track this enhancement request.
