### ISSUE TITLE
Copying Story map changes url to HTTPS

### ISSUE THREAD

**Issue by SDePinto** [Esri/ago-assistant#137]
Hello,

First of all, thanks for making this tool.  It is immensely helpful for moving different files around within our organization.

We have started making story maps that must be copied from a template and then edited for each person that it is given to.  Within the story map, there are webpage links that link to unsecured webpages(http).  Originally the story map template is also saved as a HTTP url.  When the file is copied over to a different user, it automatically changes the story map url from http to https.    This causes the story map to break and not load the webpages due to mixed securities.  I just wanted to bring this to your attention in case anyone else is experiencing this problem as well.

Thank you so much,
Shane

**Comment by GISDev01** [comment]
Hi Shane,
To clarify, you are using AGOL for organization, correct? (e.g sdepinto.maps.arcgis.com) is the root of your Storymap URL, and it is getting changed from HTTP to HTTPS after doing a 'I want to - Copy Content' operation between two different accounts within your same organization?

**Comment by ecaldwell** [comment]
Thanks for the feedback @SDePinto. This is "expected" behavior since the portal URL is always stored in `https`, but I see how this would produce problems like your mixed content error. I think the fix is to add a test [just like this section](https://github.com/Esri/ago-assistant/blob/master/src/js/main.js#L988-L991). Can you think of any potential conflicts this would introduce?

**Comment by SDePinto** [comment]
Hello GISDev1,
Yes that is what is happening in the same organization.  We are using a template story map that we have created and copying that and renaming it in order to preserve the template story map.

ecaldwell,
That is good to know, thank you for the clarification.  I'll work with my team to see if that is the solution we need(I'm not the code guru) and let you know how that goes.

Thank you both for your time

**Comment by slibby** [comment]
With the shift towards HTTPS-Only for all ArcGIS Online organizations well underway, this is no longer relevant, I am closing it at this time.
