### ISSUE TITLE
Provide option with Copy Item to also copy comments,ratings,and number of views

### ISSUE THREAD

**Issue by shaneclarke** [Esri/ago-assistant#14]
Please provide an option with the Copy Item to also copy the comments, ratings, and number of views for the source item? This would be useful when copying an item from a public account to an organization account. I don't think the Copy should automatically copy the number of views, ratings and comments as sometimes the user would not want to copy these. But, providing an option would be great.

**Comment by ecaldwell** [comment]
I have found repeated evidence that this is simply not possible. Copying items always spawns a new item and the information would all have to be faked.
