### ISSUE TITLE
Viewing a file item's json causes the file to be downloaded

### ISSUE THREAD

**Issue by tedrick** [Esri/ago-assistant#140]
As an example, view id:4497b7bb42e543b691027840d1b9092a, a tile package.  Ideally, detect the type of the item before attempting to load it's data.

**Comment by ecaldwell** [comment]
Definitely a painful experience! This was brought up in #72 so let's continue the conversation there. My thought is to set a timeout on the `/data` request and provide a button to continue loading for those times when you really do want to see the data.
