### ISSUE TITLE
Error when copying two different items with the same name

### ISSUE THREAD

**Issue by oevans** [Esri/ago-assistant#15]
I copied a web map between accounts, then tried to copy an app with the same name; however, the copy failed and I got an error that an item with the same name already exists.

Also, after the error (screenshot included), the list on the left side became non-responsive.  I could no longer expand folders, etc.

![screen shot 2013-05-02 at 10 23 50 am](https://f.cloud.github.com/assets/3215530/454214/f1d42daa-b333-11e2-8515-d2b89b33ab5c.png)

**Comment by ecaldwell** [comment]
There's an `overwrite` flag that can be set to true when creating items, but I have it explicitly set to `false` to safeguard against accidentally blasting one of your items. An easy workaround is to copy the item with the same name into a different folder. Then you can manage it as usual directly in ArcGIS Online.
