### ISSUE TITLE
Extra Save Button

### ISSUE THREAD

**Issue by gdbgeek** [Esri/ago-assistant#153]
In the "View an Item's JSON" tool would it be possible to have a floating save button (in the gutter on the right) or an extra save button at the bottom? I find (more often than not) I have to scroll down to make an edit and then scroll back up to the top to check the JSON status and save. Its rather time consuming for large webmaps. Thanks for the great tool!
![2016-11-07 15_49_27-arcgis online assistant](https://cloud.githubusercontent.com/assets/4096739/20044922/edc003a6-a501-11e6-849b-f28da26f19cd.png)

**Comment by ecaldwell** [comment]
I've run into this same pain point. I'm sure it can be solved elegantly with some changes to the css, but I'm no css wizard.

**Comment by GISDev01** [comment]
I've actually run into the same pain point as well. I'll take a look and see if I can figure out a quick solution.
