### ISSUE TITLE
AGOL Assistant doesn't work with slovak language

### ISSUE THREAD

**Issue by trichtl** [Esri/ago-assistant#162]
When opening the ARcGIS Online Assistant with a slovak language setting of a browser the site opens, but you couldn't 
sign it anymore.
[bug.docx](https://github.com/Esri/ago-assistant/files/659491/bug.docx)

**Comment by ecaldwell** [comment]
Thanks for submitting this @trichtl. This is caused by missing localizations in the underlying dojo build. That's currently being tracked in #142. I'm going to close this as a duplicate and we can continue the conversation there.
