### ISSUE TITLE
View Users Stats for Open Data Groups/Items

### ISSUE THREAD

**Issue by msokolDOIT** [Esri/ago-assistant#164]
This more of an enhancement (sorry, was logged in under wrong account the first time)
With groups & items designated for Open Data, it would be nice to see the statistics for views of those items. It does not appear you can currently do this through ArcGIS Online View Status tool or through any existing Open Data tools provided within ArcGIS Online

**Comment by sidewalkballet** [comment]
Hi @msokolDOIT - do you mean that you'd like to see data on _who_ is viewing your datasets on ArcGIS Open Data? Or overall stats on views/downloads/searches etc?

**Comment by sidewalkballet** [comment]
While we don't have stats viewable within ArcGIS Online or ArcGIS Open Data at this time, we do send statistics on dataset views, searches, and downloads by type to Google Analytics. You can create a GA tracking ID and enter it on your site configuration page -- all stats will be pushed from that point to your GA account. [Documentation here](http://doc.arcgis.com/en/open-data/provider/configure-your-open-data-site.htm#ESRI_SECTION1_564FACD5005D4F0A9F3D0F42A0E038FD). 

I can pull stats for your site retroactively if you like - feel free to send me an email with your site URL to cclaessens@esri.com.

**Comment by msokolDOIT** [comment]
Thanks - I will take a look at the Google Analytics
Would this be a feature that is potentially coming directly within the Esri Open Data platform?

**Comment by sidewalkballet** [comment]
Yes, our product plan aims to have user metrics within ArcGIS Open Data itself, but we currently don't have a timeline for it.

**Comment by ecaldwell** [comment]
Closing this out as a viable workaround was found with ArcGIS Open Data.
