### ISSUE TITLE
Copying content between portals results in a "Invalid JSON in 'text' parameter" error

### ISSUE THREAD

**Issue by jshutenasa** [Esri/ago-assistant#165]
I am trying to copy content from one portal to another, but I get an "Invalid JSON in 'text' parameter" error.  This error occurs on my local (stand-alone) AGO-A instance, as well as on the version of AGO-A hosted on the Esri site.

![image](https://cloud.githubusercontent.com/assets/20583276/22218012/26f342ac-e173-11e6-9624-3edbd345bfdb.png)

The copy error applies to multiple types of objects (e.g., Map layers and Feature layers)

Is this environment-specific (i.e., "just me"), or is it impacting other users as well?

**Comment by AnnetteF** [comment]
We are having the exact same problem when copying between 2 portals.  Is there a solution for this?

**Comment by ecaldwell** [comment]
I think it's a bug in `updateDescription.js` that got introduced with commit d1199de. It's not stripping the null value from the `text` property. I'll see if I can get this sorted out.

**Comment by ecaldwell** [comment]
>I think it's a bug in updateDescription.js that got introduced with commit d1199de. It's not stripping the null value from the text property.

Right problem, wrong place. This was actually a problem in `addItem.js`. It was fixed in f12880facb952a59b0e6c3c4504719b7abc682df which is part of PR #168. Once that gets accepted, it should go live on the site in a day or so.

Thanks for reporting this!

**Comment by jshutenasa** [comment]
Thanks for taking the time to look into the issue!
