### ISSUE TITLE
Copying content within same AGO account causes Invalid JSON in 'text' parameter error 

### ISSUE THREAD

**Issue by arcgeospatial** [Esri/ago-assistant#167]
We don't use portal but may be related to issue:

Copying content between portals: Copying content between portals results in a "Invalid JSON in 'text' parameter" error
#165 opened on Jan 23 by jshutenasa

Thanks for developing such a handy tool.  We just learned of this recently and aim to copy data items and remap service URLs to new published time series data .  Using such a nifty swiss army knife will save loads of time.  

![image](https://cloud.githubusercontent.com/assets/25965575/23234501/45a1e4aa-f920-11e6-99f5-b7746b1a7d28.png)

**Comment by ecaldwell** [comment]
Thanks for the feedback @arcgeospatial, glad you've found this tool useful.

I think you're right...this is the same underlying issue identified in #165. I just submitted a fix for this so you should see that live on the website in a day or so. I'll go ahead and close this out as a duplicate, but please feel free to reopen if you continue to see the issue after the update goes live.

**Comment by arcgeospatial** [comment]
Wow, that was super duper lightning fast!   Many thanks.
