### ISSUE TITLE
Issue  loading items with null title

### ISSUE THREAD

**Issue by apulverizer** [Esri/ago-assistant#170]
When attempting to load the items (after signing in), nothing loads and I get this error in the console.

```js
Uncaught (in promise) TypeError: Cannot read property 'toUpperCase' of null
    at http://ago-assistant.esri.com/js/main.min.js:2:23953
    at Array.sort (native)
    at Array.sort (http://ago-assistant.esri.com/js/lib/portal.min.js:2:14266)
    at F (http://ago-assistant.esri.com/js/main.min.js:2:23924)
    at http://ago-assistant.esri.com/js/main.min.js:2:24682
```

It appears to be breaking when sorting a null title. Below is the line minified line that breaks:

```js
F(f.items, "title"),
```

where F is defined as: 

```js
      F = function(a, b) {
        a.sort(function(a, c) {
            var d = a[b].toUpperCase()
              , e = c[b].toUpperCase();
            return d < e ? -1 : d > e ? 1 : 0
        })
```

**Comment by ecaldwell** [comment]
Maybe an easy fix is to replace null titles with `""` before the test. I'll take a swing at it. I'm curious how you ended up with items with null titles. Is it naturally occurring or is this a side effect of a custom workflow?

**Comment by apulverizer** [comment]
Yeah that might work. I believe a few of the titles are null for internal testing of various apps (I'm also at Esri).

**Comment by slibby** [comment]
@ecaldwell can this issue be closed now?
