### ISSUE TITLE
SSL Certificate has expired for the site.

### ISSUE THREAD

**Issue by swwendel** [Esri/ago-assistant#179]
In Chrome, when going to https://ago-assistant.esri.com the page shows Not Secure and warns the user. In viewing the certificate for the site, it appears that the certificate expired on 4/26/2017.

![image](https://cloud.githubusercontent.com/assets/6974399/25496121/d014a1e0-2b4d-11e7-86c3-9c72f2550a3a.png)

**Comment by jgravois** [comment]
thanks for reporting! i've never gotten involved with pushing to production before, but i'll check into this now.

**Comment by ecaldwell** [comment]
@rwmajor2 is on this and should have the new cert live early next week.

**Comment by rwmajor2** [comment]
@swwendel Resolved.
