### ISSUE TITLE
Don't understand why need to Register the app in the Portal.

### ISSUE THREAD

**Issue by lwconquer** [Esri/ago-assistant#184]
I am trying to modify the code for the Ago-Assistant, and find that I need to register the app in my Portal to obtain an 'appId' for OAuth dialog to log in first. But I don't know how and why should I do this. 

To try to register it in Portal, from the Portal's 'Add Item', I chose 'An Application', and then it give me several optional types: Web Mapping, Mobile, Desktop, Application, and Application Extension. I don't know how should I fill the info in this page.

Besides, I have some hard time to put up the project in Visual Studio, particularly on how to use NPM and Grunt in Visual Studio 2015.

Thanks,
Wei

**Comment by jgravois** [comment]
> I need to register the app in my Portal [...] I don't know how and why should I do this.

I'd recommend checking out our documentation on [OAuth2](https://developers.arcgis.com/authentication/what-is-oauth-2/) and [Implementing Named User Login](https://developers.arcgis.com/authentication/signing-in-arcgis-online-users).  

The gist of it is that when you create an application item and register it you're creating a placeholder to make sure our platform knows that its safe to pass back short-lived tokens.

> and then it give me several optional types:

Since ago-assistant is a web application, 'Web Mapping' is the right choice here.

> how to use NPM and Grunt in Visual Studio 2015.

npm and grunt are both invoked via the command-line.

**Comment by ecaldwell** [comment]
Also, you don't actually need to do the app registration step to use this app with your Portal. That's only if you want to use OAuth. You can use simple authentication by choosing the "Log in to Portal for ArcGIS" option.

**Comment by lwconquer** [comment]
Thanks, Evan. We are using SAML to authenticate our user. I think I still
need to register the app in this case, correct? I heard SAML is pretty
similar as OAuth. And what URL should I specify while registering it on
Portal with choosing 'Web Mapping' option?

Many thanks,
Wei

**Comment by jgravois** [comment]
to be clear, the `master` branch of this repo doesn't currently support OAuth2 logins to portals (whether they utilize SAML or not).  

> We are using SAML to authenticate our user. I think I still
need to register the app in this case, correct?

@ecaldwell is correct that an older school technique to login to Portals is supported, the catch is that SAML identity providers require an OAuth2 approach and that that approach requires you to register your own app.

> And what URL should I specify while registering it on Portal with choosing 'Web Mapping' option?

Its not crystal clear in the doc i linked previously, but it doesn't matter what url you specify when you create the item.  in contrast, it is crucial that you specify redirect uris that correspond to the actual location of your app.

i have isolated some changes in https://github.com/Esri/ago-assistant/pull/180 that so far have proven sufficient to get folks logged into a SAML Portal using OAuth2 (via the Log in to ArcGIS Online). if you're interested in helping test that work, that'd be great.

**Comment by slibby** [comment]
@jgravois we are working on supporting OAuth across both source and destination (for Portal) in a separate branch which should resolve this issue shortly..

**Comment by rwmajor2** [comment]
Addressed by PR #194.
