### ISSUE TITLE
Unable to view Folders (Root or Any) after login 

### ISSUE THREAD

**Issue by ChandlerChang** [Esri/ago-assistant#185]
Hi, 
I am not able to see any folder and its content. Please find the attached screenshot 
![image](https://cloud.githubusercontent.com/assets/28734482/26113412/519fb4d2-3a0f-11e7-808e-fea15637021e.png)

**Comment by ecaldwell** [comment]
Are there any messages are in the developer console?

**Comment by ChandlerChang** [comment]
Hi ,We are getting these errors .Please check below screenshot.
![image](https://cloud.githubusercontent.com/assets/28734482/26148233/d8bec02a-3aaa-11e7-8a23-8d863f9e833d.png)
![image](https://cloud.githubusercontent.com/assets/28734482/26148373/454f0600-3aab-11e7-95d7-0f02e22cfc97.png)

We are able to connect other organization portal and able to see folder but not for this one.

**Comment by rwmajor2** [comment]
@ChandlerChang You are running into a CORS issue.  Do you know if the webserver is CORS enabled?  Is it IIS or Apache/Tomcat?

**Comment by ecaldwell** [comment]
I just noticed in the first screenshot that there is a certificate error. 

@rwmajor2 Could that be causing trust issues in chrome?

@ChandlerChang Have you tried a different browser?

**Comment by ChandlerChang** [comment]
@rwmajor2   i m using IIS
@ecaldwell I tried in IE and Mozilla Firefox, facing same issue.

**Comment by ecaldwell** [comment]
Is this portal using IWA? Do you get those same certificate errors in the other browsers? The certificate should be valid for the site.

**Comment by ChandlerChang** [comment]
Yes .I am using IWA.
I am getting certificate error in IE and Firefox.
But i am able to view folders for another Portal only problem occurring for this one.
I used same machine before to login through AGO assistant  and it was working fine .

**Comment by ChandlerChang** [comment]
Any updates on this issue?

**Comment by ecaldwell** [comment]
Did you verify you have CORS enabled per @rwmajor2's suggestion?

**Comment by CraigCleveland** [comment]
@ChandlerChang if you're not familiar with enabling CORS in IIS here is the snippet you need - https://enable-cors.org/server_iis7.html

**Comment by ChandlerChang** [comment]
@CraigCleveland  Thanks.
@ecaldwell  I enabled CORS in IIS , Now am getting these errors in console.
![image](https://cloud.githubusercontent.com/assets/28734482/26215141/07b9152e-3bb4-11e7-9fb9-7485b7f6fcf7.png)

**Comment by ecaldwell** [comment]
Do you have a valid certificate installed on your portal's Web Adaptor? Are you getting the same error in other browsers?

**Comment by CraigCleveland** [comment]
@ChandlerChang are you trying to go through 7443 when connecting to your Portal?  Or via your Web Adaptor?  If you're going through 7443  you may want to consider replacing the self signed cert on that endpoint and see if that resolves the issue.  Alternatively just use the web adaptor which will make life easier.

**Comment by ChandlerChang** [comment]
I am getting this error in console 
![image](https://cloud.githubusercontent.com/assets/28734482/26253501/79d35d2c-3c68-11e7-97d2-eb109714fe75.png)

**Comment by ecaldwell** [comment]
When do you get that error? On initial page load or when trying to log into your portal? Does your portal present a valid certificate?

**Comment by ChandlerChang** [comment]
When I tried login to portal

**Comment by ecaldwell** [comment]
We can't really help you troubleshoot this unless you provide more information such as verifying your portal is presenting a trusted certificate. We've confirmed the app is working with portals secured with IWA so these errors appear to be unique to your particular environment. I'm going to mark this as `not reproducible` and close it out.

If you're able to verify the additional troubleshooting steps that have been suggested then I will gladly reopen this.

- [ ] Confirm a trusted certificate is being presented by the portal.
- [ ] Verify you are connecting via the portal's web adaptor.
- [ ] Verify you get a consistent error message in other browsers (Chrome is particularly stringent about certificates).
