### ISSUE TITLE
If JSON doesn't pass validation highlight issue

### ISSUE THREAD

**Issue by l84tahoe** [Esri/ago-assistant#199]
When validating the JSON of an item, it would be nice to have where the error occurs highlighted.

**Comment by jgravois** [comment]
> nice to have

absolutely! if you're interested in taking a crack at it, i'd be more than willing to offer guidance.

**Comment by slibby** [comment]
This is addressed by #194 - the first line that errors in the JSON is highlighted in red.

**Comment by rwmajor2** [comment]
Addressed by PR #194.
