### ISSUE TITLE
Enhancement: Allow copying of item /resources 

### ISSUE THREAD

**Issue by slibby** [Esri/ago-assistant#200]
Story Maps and other apps use the /resources endpoint to store images (ex. http://www.arcgis.com/sharing/rest/content/items/7c72e12d01f44c47b224b6fd8e54daaa/resources/) - an enhancement to AGO Assistant would allow the app to copy /resources when copying an item that includes them (and reference them directly in the new version).

**Comment by oevans** [comment]
Duplicate of #181  ;-)

**Comment by slibby** [comment]
Ah, sorry, someone from your team suggested it so I figured it wasn't already there :(
