### ISSUE TITLE
Feedback on new release; UI tweaks

### ISSUE THREAD

**Issue by rwmajor2** [Esri/ago-assistant#205]
* Consider putting the Org name and URL on different lines so the URL doesn’t wrap (looks awkward when it does) – or just make the org name a hyperlink and remove the raw URL.
* Maybe remove the “refresh” label to increase space for long user names/real names. Consider moving it to a tooltip saying “Refresh item list” to clarify what it’s refreshing (as opposed to refreshing the JSON).
* Consider removing “Current user”-- it’s obvious what that information is like the org name. If you don’t want to remove consider changing that label to “Current member:” or “Logged in as:” since “user” is a specific role name.

**Comment by slibby** [comment]
@codylawson please take this feedback into account (if relevant) in your mocks.
