### ISSUE TITLE
ArcGIS Online login error

### ISSUE THREAD

**Issue by JasonSawle** [Esri/ago-assistant#207]
Hi

Just trying to login to the app via the ArcGIS Online button but it gives this error:

HTTP ERROR: 503

Problem accessing /oauth2/authorize. Reason:

    Service Unavailable

The Portal button works fine. Thanks

Jason

**Comment by rwmajor2** [comment]
@JasonSawle We are looking into it.  In the interim, you can also use the Portal login but use https://www.arcgis.com as your URL.

**Comment by ecaldwell** [comment]
@rwmajor2 I think this may be as simple as removing the trailing slash from `config.portalUrl` in `package.json`. The [documentation for the OAuth constructor](https://developers.arcgis.com/javascript/3/jsapi/oauthinfo-amd.html#portalurl) indicates it isn't needed.

Initial testing shows the fixes the OAuth login issue. Can you think of any other implications this would have in other areas of the app?
