### ISSUE TITLE
HTTP 503 Error accessing assistant

### ISSUE THREAD

**Issue by talllguy** [Esri/ago-assistant#209]
I'm currently having trouble accessing the assistant. I'm using an incognito session to verify it is not a cookie issue. However, it does occur when in a regular (non-incognito) chrome session.

![image](https://user-images.githubusercontent.com/1827881/30704286-418cb84a-9ec0-11e7-9436-cc6d221af6ab.png)

**Comment by rwmajor2** [comment]
Duplicate of #207.  This has now been fixed.  Might need to refresh your browser cache.
