### ISSUE TITLE
Full copy of Feature Service not working

### ISSUE THREAD

**Issue by sptm1107** [Esri/ago-assistant#215]
I am attempting to copy Feature Service files to another ArcGIS account using Full Copy; however, the copy status gets stuck on "Creating Service," never actually copying. Is there anything specific I should be looking for to troubleshoot this? Thanks for your time.

**Comment by ecaldwell** [comment]
There will be some additional messaging in the developer console. Can you share what you see there?

**Comment by slibby** [comment]
@sptm1107 does your service have related tables/layers within it?

**Comment by ecaldwell** [comment]
@slibby This should be closed due to inactivity.

**Comment by jlmarino** [comment]
In case it helps anyone in the future who finds this issue: I encountered the same problem, and in my case it was because the target user account did not have permission to create a Feature Service.
