### ISSUE TITLE
Header overlaps content on narrow windows

### ISSUE THREAD

**Issue by andreasulmer** [Esri/ago-assistant#228]
On narrower views, header line-breaks, and overlaps content, making certain actions unusable (e.g. see first item(s) on search). Already happens on half of a hd screen (width:960px), which I consider an often used window size.

Fix:
* avoid line-breaking of header
* or move content down with growing header (don't overlap)

![ago-assistant-header-overlap](https://user-images.githubusercontent.com/25357523/33184833-13fb472a-d07f-11e7-8ed8-33804452f828.gif)

**Comment by rtm** [comment]
I divide my 2560x1080 screen into three vertical panels, so each is about 850px. Many/most applications or websites work just fine at such a width. There is no good reason that GitHub should not display in usable fashion in a window of such a width. Instead, content extrudes invisibly off the right side of the window.

**Comment by slibby** [comment]
This is definitely something that should be better, but may be a low-hanging fruit for now compared to functional requests. Styling needs to be reviewed overall, but that is a significant undertaking.

**Comment by slibby** [comment]
Closing as low priority, since we are considering a full UI update.
