### ISSUE TITLE
One portal doesn't show up, the other does

### ISSUE THREAD

**Issue by Tom-Thumb** [Esri/ago-assistant#230]
After crashing our internal portal (following an esri tech support instruction), I was unable to bring content back in after re-installing. Much of the same content exists on our external facing portal, so I want to copy from there to the internal facing one. AGOL Assistant would be the perfect tool if I could make it work.

The source portal comes in, showing folders with content just fine, but the destination portal lets me log in, but shows nothing. If I choose "view my content" it shows the portal name, URL, and my username, but no folder names or content. If I choose "view my groups" it shows the group names, and a number for the items in each one. If I click on a group name, it shows the content in that group, but still no folder names. 

So, if I start AGOL Assistant by logging into the other portal, I see content and folders listed at startup, but when I go to "copy content" and log into the problem one, it just puts the name there, no folders, so there's nowhere to drag the content. I've tried creating new folders, groups, everything I can think of, and nothing changes the behavior. Esri tech support won't help because it's not supported. 

Any idea what I can do?

**Comment by Tom-Thumb** [comment]
Follow-up: the above behavior was in IE11. When I try to log into that portal on Firefix, it just tells me it's a bad URL, and that I need a URL for my webadaptor. I copy and paste the URL from my Portal session in, and it still fails. No problem logging on to portal with that url...

**Comment by ecaldwell** [comment]
What do you see in the browser's console when you try in Firefox? Is your portal using vanilla authentication or is it something else like IWA?
