### ISSUE TITLE
Update Help Link to correct URL.

### ISSUE THREAD

**Issue by rwmajor2** [Esri/ago-assistant#235]
Currently, this link is broken.

![image](https://user-images.githubusercontent.com/3799165/36079972-35f2e560-0f57-11e8-8c73-0a15826dd704.png)

It needs to be updated to `https://developers.arcgis.com/rest/users-groups-and-items/working-with-users-groups-and-items.htm`.

**Comment by slibby** [comment]
closed via https://github.com/Esri/ago-assistant/commit/d5d4a9b93cec3e01ca318a46b6e3b0ea005a722c
