### ISSUE TITLE
Copy new Dashboard items not supported

### ISSUE THREAD

**Issue by glasnerph** [Esri/ago-assistant#236]
Dear colleagues,

I wanted to copy dashboards within portals. Unfortunately this is currently not supported. Any plans to do so?

Thanks,
philip

**Comment by ecaldwell** [comment]
This was enabled in #223, but I see that it's not working now. 

@apulverizer @rwmajor2 The dashboard type [is listed](https://github.com/Esri/ago-assistant/blob/master/src/js/main.js#L1815) in `isSupported`. Any thoughts on why it wouldn't be working?

**Comment by apulverizer** [comment]
@ecaldwell When I build it locally with latest master branch it works as expected. 
On the hosted app, it doesn't work (the dashboard is not enabled for copying).

**Comment by ecaldwell** [comment]
@apulverizer The hosted app usually lags the master repo a bit so that makes sense. Thanks for tracking that down. I'll check with @rwmajor2 on getting an updated version pushed up.

**Comment by slibby** [comment]
@rwmajor2 Can you verify that the latest released version on GH is hosted on S3 as well?

**Comment by thisguymaps** [comment]
Still running into this issue over a year later. Any updates or estimated timeline? @ecaldwell @rwmajor2

**Comment by heathergabrielsmith** [comment]
I have also had this problem. Is there any known workaround?

**Comment by brotherpup** [comment]
Still not working. Is there a work around? Maybe through the Python API.

**Comment by apulverizer** [comment]
@brotherpup you can try the `clone_items` method in the python api, though that would clone all of the underlying maps and services as well. 
https://esri.github.io/arcgis-python-api/apidoc/html/arcgis.gis.toc.html#arcgis.gis.ContentManager.clone_items

There is also an example showing how to just copy the item and not the underlying data:
https://developers.arcgis.com/python/sample-notebooks/clone-portal-users-groups-and-content/#Copy-Items

You can also just `Save As` in the Dashboard web app to make a copy

**Comment by slibby** [comment]
Covered by #267 - closing.
