### ISSUE TITLE
Looking for assistance contributing to this project

### ISSUE THREAD

**Issue by tforward** [Esri/ago-assistant#237]
I have some work I'd like to contribute to this project but in some areas of the app I'm at a loss how how to do what I want.

 In short I'm trying to add an additional button to the [Copy][Save][Edit] in the view JSON panel, to which I can add some new content. Is there one of the existing contributors to this project that can lend some time in helping me get this part going?

Thanks

**Comment by ecaldwell** [comment]
@tforward I'm happy to help you get started. Message me on [The Spatial Community](http://thespatialcommunity.org/) slack at @ecaldwell.

**Comment by tforward** [comment]
Cool will do, just waiting for the invite to come through The Spatial Community
