### ISSUE TITLE
Doesn't work with WAB dashboard template if "Info Summary" widget is used.

### ISSUE THREAD

**Issue by setldsolutions** [Esri/ago-assistant#238]
Fought this for a couple hours.  Thought my app was corrupt.  Rebuilt to a skeleton.  Same issue.

Have another dashboard template app that allows ago-assistant to mod JSON -- looked for diffs.  

Removed Info Summary widget from new app.  Works again.

**Comment by ecaldwell** [comment]
Can you clarify what part doesn't work? Was it a specific action (e.g. editing json, copying, etc)? Can you share the summary widget section of the json?

**Comment by setldsolutions** [comment]
Cannot even see the JSON - tried multiple browsers, high powered machines.

 

*	Best I got was "old Firefox on i7 12 core 128gb ram Windows Server
2016 machine could see full Desc but 336k blank rows of JSON in the Data
section".  New Firefox = nope.  Chrome = nope.

 

*	Second best was "Edge on i7 workstation 64gb ram could see Desc and
Data 'frames', not expanded, no rows"

 

*	All other combos crashed.

 

I removed the "Info Summary" widget and the JSON popped up right away.

 

My hunch is that the issue lies in the way the "Info Summary" symbolizes
things (e.g. redefines them from the service, individually in JSON - making
an unnecessary bloat of rows).

 

I  think 336k rows is about 2x the most I've ever seen / used in AGO
Assistant.

 

 

Regards,

 

Jacob Maggard

 

832-563-5699

 <mailto:jacob.maggard@setld.com> jacob.maggard@setld.com

 <http://www.setld.com/> www.setld.com

**Comment by setldsolutions** [comment]
Cannot even see the JSON – tried multiple browsers, high powered machines.

•	Best I got was “old Firefox on i7 12 core 128gb ram Windows Server 2016 machine could see full Desc but 336k blank rows of JSON in the Data section”.  New Firefox = nope.  Chrome = nope.

•	Second best was “Edge on i7 workstation 64gb ram could see Desc and Data ‘frames’, not expanded, no rows”

•	All other combos crashed.

I removed the “Info Summary” widget and the JSON popped up right away.

My hunch is that the issue lies in the way the “Info Summary” symbolizes things (e.g. redefines them from the service, individually in JSON – making an unnecessary bloat of rows).

I  think 336k rows is about 2x the most I’ve ever seen / used in AGO Assistant.

**Comment by ecaldwell** [comment]
Gotcha. Do you agree that a short summary of this is that the Info Summary widget can potentially bloat an item's json to unmanageable sizes? Can you share any details about the service (e.g. # of sublayers) or anything else that might have contributed to the sheer size?

In the meantime, maybe a test could be added to warn when the json payload is over a certain size. That, or we just add "Core i7 with 64GB RAM" to the readme as Recommended Specs. :wink: 

Thanks for sharing this one!

**Comment by setldsolutions** [comment]
I think so.  That's my hunch.  The service was a tiny service with about 6 layers - 2 feature layers called by Info Summary.  Not much config, either!  Doesn't get much simpler on my side (on purpose).

Yeah, I think the largest manageable row count I've messed w/ previously with is 150-200k.

I sent this to my Esri rep as well.  There's no reason for Info Summary to re-sym fill and outline for 20k unique items, especially when I asked it to eat the default sym from the service.

**Comment by slibby** [comment]
Closing as an issue with the Info Summary widget
