### ISSUE TITLE
copy content and datasources for ArcGIS Server services from Linux to Windows

### ISSUE THREAD

**Issue by deRightDirection** [Esri/ago-assistant#241]
I have a portal running on linux with services, those services uses a database on a different machine
I build maps on tops of those services in Portal

now I want to migrate my maps and services to Portal on Windows. The AGOL Assistant can do this for me even including building new services. But use those new services also the same database or do I get a copy of the data into the ArcGIS datastore?

**Comment by slibby** [comment]
@MannusEtten AGO-Assistant primarily works with what we call the Portal/Online "sharing" API - which controls items, hosted services, app references, users, groups etc.

In this case we do not yet have a way of republishing database-backed map services using AGO-Assistant, I would suggest looking into the Python API + arcpy if you want an automated way of doin this, there are a few somewhat similar examples:

- https://developers.arcgis.com/python/sample-notebooks/publishing-sd-shapefiles-and-csv/
- https://enterprise.arcgis.com/en/server/latest/administer/linux/scripting-service-publishing-with-arcpy.htm

**Comment by MannusEtten** [comment]
thanks for your answer at least 👍

**Comment by slibby** [comment]
This has been discussed and the project team agreed that this kind of service migration is not a target for AGO-Assistant
