### ISSUE TITLE
Transferring data using ArcGIS Online Assistant

### ISSUE THREAD

**Issue by abdulnishar** [Esri/ago-assistant#242]
I am trying to transfer data from a one to Portal for ArcGIS to another using ArcGIS Online Assistant - https://ago-assistant.esri.com/.
Not sure how to actually synchronise the data after the “Drag and drop” step.

**Comment by slibby** [comment]
Hi there @abdulnishar - what kind of item are you trying to copy from Portal to Portal? If you are copying a Web Map, there is nothing else required after the drag and drop - it should confirm that it copied properly. If you are copying a hosted service, be sure to copy using the "Full" option. If you can provide more details of what you are trying to copy, I can provide better advice.

**Comment by slibby** [comment]
@abdulnishar If this is no longer an issue, I will close the Issue, if you are seeing a problem, could you please share some more details so we can identify whether it is a bug or a workflow challenge?
