### ISSUE TITLE
Export/Import Items to JSON

### ISSUE THREAD

**Issue by aryan200o** [Esri/ago-assistant#243]
Hi there,
I was wondering if this enhancement could be considered.
To allow users to export/import items (eg. map/feature service, webmap, webapp) to json files? This would allow the user/admin to backup their items to local disk/network fileshare/git repo in case of a portal crash, etc.
The json file would contain all of the configuration, etc. (eg. name, desc, sharing, thumbnail) to recreate the item again. Further enhancement could be a compare functionality to see what has changed on the item as compared to what has been saved to allow the administrator to restore the item's approved configuration.

Thanks

**Comment by slibby** [comment]
@aryan200o I would look at the ArcGIS Python API for this - I think it will provide more functionality for what you're looking for. Currently with AGO-Assistant we do provide a JSON view, but paginating through all content and exporting it is a better use for the Python API in my opinion.

https://developers.arcgis.com/python/sample-notebooks/
