### ISSUE TITLE
Full copy from AGOL to portal

### ISSUE THREAD

**Issue by bkaplan1** [Esri/ago-assistant#251]
I'm attempting to use the ArcGIS Online Assistant https://ago-assistant.esri.com/# to copy data from Online to Portal.  When Copying, there is an option to copy a reference to the data or to copy the Full dataset.  The option to copy the full dataset is identified as experimental.  I'm reporting that when I attempt to copy a Full data set with that consists of a single layer or a Feature Collection (multiple layers), it results in a "Incomplete-check console" message.  When I check the copied data, the tables show up with the columns with no rows or sometimes with all the rows but with empty cells.   Thanks for expanding Assistant to include this tool. This tool will be very useful.

**Comment by kirkchesla** [comment]
Did you get any resolution to this issue?

**Comment by slibby** [comment]
I do know that full copy works pretty well for most layers, it may have specific issues with this exact one. Unfortunately there's no support for further development of the tool at this time.

**Comment by slibby** [comment]
There are a variety of issues with the deep copy functionality that will be looked at, closing this for now.
