### ISSUE TITLE
Log in to ArcGIS Online error

### ISSUE THREAD

**Issue by anthonyryan-ergon** [Esri/ago-assistant#252]
I have the tool deployed on an internal organisational server and when I chose to log in to ArcGIS Online I receive Invalid redirect_uri Error 400
![ago assistant - agol login](https://user-images.githubusercontent.com/19471219/52189150-a3c58080-2882-11e9-90be-78ac5ad36019.png)

Is there a config or something to rectify this?

I can get to AGOL if I use the portal option and enter the url manually

Thanks

**Comment by slibby** [comment]
@aryan200o Did you update the AppID in the config file to use your own that you would have created in ArcGIS Online? Check out the "building the app" section in the Readme: https://github.com/Esri/ago-assistant/blob/6a336e8936c8850e8a28b03df59cc9a741bf2ab1/README.md

**Comment by slibby** [comment]
closing with no response
