### ISSUE TITLE
AGOL Assistant and Portal

### ISSUE THREAD

**Issue by droberge2015** [Esri/ago-assistant#253]
Hello

I am trying to setup AGOL-Assistant (https://ago-assistant.esri.com/) with my Portal (10.6.1)( using a SAML-based Identity Provider ADFS). I created an app, setup the redirect URI and register the app. Each time I try to login using the app ID, the ONLY url available is www.arcgis.com

What am I missing?

thanks!

**Comment by slibby** [comment]
Hello, simply replace the arcgis.com URL with your Portal URL and App ID and you should be ok:

![image](https://user-images.githubusercontent.com/1691225/53255632-3fc4f980-3683-11e9-80e4-84818c1a9dc7.png)

**Comment by droberge2015** [comment]
well, I've tried that and doesnt seem to like it:

![image](https://user-images.githubusercontent.com/11433967/53256117-c03c2800-368c-11e9-9ee7-6729df28fce5.png)

**Comment by droberge2015** [comment]
OK making progress...

I was able to signin using the internal url  (https://servername:7443/arcgis/home/) BUT... the content is EMPTY

![image](https://user-images.githubusercontent.com/11433967/53256710-1f4e6c80-368e-11e9-90f0-a145b3b6b405.png)

**Comment by slibby** [comment]
Are there any errors in the browser developer tool console or failed requests in the network tab?

**Comment by droberge2015** [comment]
![image](https://user-images.githubusercontent.com/11433967/53258235-bcf76b00-3691-11e9-8f30-b37b5622717c.png)

**Comment by slibby** [comment]
Is your IIS web server for Portal configured to provide an Access-Control-Allow-Origin Header?

**Comment by droberge2015** [comment]
yep

**Comment by slibby** [comment]
Is Windows Authentication enabled on your Portal Web Adaptor? If you try the same workflow as this image depicts: https://user-images.githubusercontent.com/11433967/53256117-c03c2800-368c-11e9-9ee7-6729df28fce5.png does it trigger any failed network requests in the browser console?

**Comment by droberge2015** [comment]
sorry for the delay, I've been out sick the past few days...yes windows AUTH is enabled and no I am not getting network issues.

but look at error message below (multiple  'Access-Control-Allow-Origin' values)....how/where do I fix that? That's above my pay grande :(

because if I click on the hyperlink, I can see all the JSON code of all items of the Portal...

Access to XMLHttpRequest at 'https://giswebtest.cityofames.info/arcgisdevportal/sharing/rest/portals/self?token=d7l6Mr2u8vUQpaI9BcLUtAkxJ14PbfjbvK_9yB1Q_S6_DEQAr50eK1j8dr6SAPrdI40f4D0gQOBvv12yQIFQaqE48ZWfjE95RVawhe0AtIzFNLCY4Q5zVdpVZZAwfJCyBxHznaLF8xxg2JFVC_0N5G5ixOhOvk7ytzXi05JZ-zqZLsQ2PxfH0BZk5TE8u4XI_v5zfysDJTlLHI1yGOGO_7O40ps2fjXeIOJanMKChLM.&f=json' from origin 'https://ago-assistant.esri.com' has been blocked by CORS policy: The 'Access-Control-Allow-Origin' header contains multiple values 'https://ago-assistant.esri.com, *', but only one is allowed.

![image](https://user-images.githubusercontent.com/11433967/53517890-57421f00-3a95-11e9-970e-2a7ed5c68004.png)

**Comment by droberge2015** [comment]
got it!

I removed the Access-Control-Allow-Origin (*) entry from IIS and everything startd working. Sorry for the trouble

**Comment by slibby** [comment]
resolved!
