### ISSUE TITLE
AGO Assistant crashes out to login page

### ISSUE THREAD

**Issue by jamisondent** [Esri/ago-assistant#254]
I'm seeing some strange behavior in ArcGIS Online Assistant when using the tool, "Update the URLs of Registered Apps and Services" in Portal.  When selecting the URL of an item and then clicking either the Reset or Update button, AGO Assistant crashes out to the login page.  If I clicked the Update button, I do later find that the update was actually done.  Similarly, though not catastrophically, performing the same action when in ArcGIS Online rather than Portal, I see the login page flash briefly before returning to the page in AGO Assistant.  This happens in IE, Chrome, and Firefox.

Does anyone have any idea what's going on and how I might fix it?

Thanks,
Marc

**Comment by jamisondent** [comment]
Suddenly this afternoon, it is now working properly in Chrome and Firefox, but not IE.

**Comment by jamisondent** [comment]
More strange behavior.  I thought it was only coincidence yesterday when Chrome started working after I brought up Fiddler, but it happened again today.  The problem was observed in Chrome where the app crashed out to the login page.  I brought up Fiddler and logged into the app again, and it started working again.  Firefox continues to work regardless, but it never did before, and IE never works.

**Comment by jamisondent** [comment]
Back to no browsers working.  Very frustrating.

**Comment by slibby** [comment]
Sorry to hear that - I can confirm it's working for me in Chrome against a 10.6.1 Portal. I did see the "crash out to login page" happen once but haven't been able to reproduce it myself. Can you share a specific click by click workflow so we can try that too?

**Comment by jamisondent** [comment]
Since I forgot to mention it, I'm using Portal 10.5.1.

Here's the workflow:
- Open AGO Assistant at https://ago-assistant.esri.com/ 
- Select "Log in to Portal for ArcGIS
- In the Direct Login tab, enter the URL (https with FQDN) and my name/pw (Active Directory), and click the Log in button
- From "I want to...", select "Update the URLs of Registered Apps and Services"
- Open a folder and select a blue highlighted item of either type.
- On the right, where the item URL is displayed, click either Reset or Update, whether or not a change is made to the URL.
- The application crashes out to the login screen. This does not happen when using "Update the URLs of Services in a Web Map"
- Login again and observe that, if a URL Update was made, it was indeed updated on that item.

That's all it is.  Seems like a straightforward workflow.

Thanks,
Marc

**Comment by slibby** [comment]
It seems like it may only happen the first time? I definitely saw the same thing but now I do not. May be something to do with stored credentials? We have seen a number of Chrome issues with that recently. 

If you try an Incognito window is it reproducible?

**Comment by jamisondent** [comment]
No, it happens every time.  I've cleared history and cache, and I tried incognito.  I also tried another  workstation which likely has never even run the app.  No luck.  At this point, I've spent enough time on this and need to move on.  We'll just have to make our Portal URL changes manually.
