### ISSUE TITLE
Add icon for new StoryMap item type

### ISSUE THREAD

**Issue by oevans** [Esri/ago-assistant#258]
Items of the new StoryMap item type show with a document icon. Add support for the StoryMap icon.

![Screen Shot 2019-07-15 at 9 46 14 AM](https://user-images.githubusercontent.com/3215530/61221086-b7083200-a6e5-11e9-82e6-b4964d33ee7d.jpg)

This is the icon for this item type as shown in ArcGIS Online:
![Screen Shot 2019-07-15 at 9 48 04 AM](https://user-images.githubusercontent.com/3215530/61221088-b8395f00-a6e5-11e9-9894-9612dda55650.jpg)

**Comment by slibby** [comment]
captured in #267
