### ISSUE TITLE
Portal 10.3.1 support

### ISSUE THREAD

**Issue by jplunkett1** [Esri/ago-assistant#260]
Hi there
I have come across an issue that Portal 10.3.1 content does not display.
Is this expected with the new TLS requirements?

**Comment by slibby** [comment]
Hi @jplunkett1  I have not see that as we don't have a 10.3.1 Portal available to test against. Have you tried several different browsers? Are there any console errors to point to? Or failed network requests?

**Comment by jplunkett1** [comment]
Ill ask my customer to see if he can use a different browser and get those console errors.
However he signs in successfully - it looks like we are getting CORS errors.
This is an internal portal as well 
![image](https://user-images.githubusercontent.com/7854161/62671883-a5683080-b9ec-11e9-8bbd-2230f9865856.png)

**Comment by slibby** [comment]
I would suggest to direct your user to enable CORS on the Portal Web Adaptor server (in IIS or whatever they are using), following https://enable-cors.org
