### ISSUE TITLE
Transfer files

### ISSUE THREAD

**Issue by Du-Starter** [Esri/ago-assistant#279]
Hi everyone, 
This is my first time to transfer AGOL to Portal. Although the web map can transfer successfully, the Feature Layer (hosted) always occurred incompleted/ failed or take more than 5 hours upload and didnt succeed. I am wondering whether someone has the same problems and how did you figure them out!
Thanks,

**Comment by slibby** [comment]
Hello @Du-Starter  I would suggest using the ArcGIS Python API and the `clone_items` method to migrate content from Online to Portal.
