### ISSUE TITLE
"Out of Memory" Error when Viewing JSONs

### ISSUE THREAD

**Issue by BHS-SC** [Esri/ago-assistant#290]
The last couple weeks, when trying to edit a json with ArcGIS Online Assistant, after clicking on the item I want to view the json of, AGOL tries to load it, but invariably always ends up giving the Out of Memory error code.
![image](https://user-images.githubusercontent.com/54997242/189179978-f048be17-92b5-4032-92ed-7a6328f48df7.png)

**Comment by liucartography** [comment]
I've been having the same issue attempting to view the json of a massive web map. I'm trying to avoid having to rebuild the webmap just to repoint the itemids. Have you found a work around?

**Comment by BHS-SC** [comment]
Yes, using it in the Firefox browser worked for me. Also, it looks like there is a new version of AGOL assistant too.
