### ISSUE TITLE
Publish a new hosted feature service when copying hosted feature services

### ISSUE THREAD

**Issue by ecaldwell** [Esri/ago-assistant#3]
Use the method described here http://www.arcgis.com/apidocs/rest/publishitem.html#desc to publish a new Hosted Feature Service in the destination account using the source item as the input.

Some checks that will be needed:
* destination account needs publish priveleges
* a warning on credit consumption

**Comment by amarinelli** [comment]
Here is an updated link to the [Publish Item](http://resources.arcgis.com/en/help/arcgis-rest-api/index.html#/Publish_Item/02r300000080000000/) operation.
