### ISSUE TITLE
Enhancement: Update Content URL and Item ID

### ISSUE THREAD

**Issue by jacksoe** [Esri/ago-assistant#38]
It would be nice to also be able to update the itemId for an operational layer.  From the documentation I see this about the itemId: 

"Optional string containing the item ID of the service if it's registered on ArcGIS Online or your organization's portal. The web map applies any styling and pop-up information contained in the saved item."

If the map benefits from pop-ups defined by the registered service, and that id has changed, then it would be necessary to change it too.

**Comment by ecaldwell** [comment]
You can now do this by editing the JSON directly (added in #64). Let me know if you have a chance to try it out.
