### ISSUE TITLE
Add Create New Feature Collection tool

### ISSUE THREAD

**Issue by ecaldwell** [Esri/ago-assistant#46]
Accept free text entry of Esri JSON or GeoJSON (converted with [Terraformer](https://github.com/Esri/Terraformer)).

**Comment by slibby** [comment]
This is pretty well-served by the ArcGIS for Developers Site at this time.

![image](https://user-images.githubusercontent.com/1691225/72449100-5bdaf900-3775-11ea-8844-3b2959a2f9e2.png)
