### ISSUE TITLE
Support for Integrated Windows Authentication in Portal for ArcGIS

### ISSUE THREAD

**Issue by jmirmelstein** [Esri/ago-assistant#54]
More often than not, Portal for ArcGIS implementations are done using Integrated Windows Authentication.  Support for IWA in authenticating against a Portal would be a fantastic addition to this tool!

**Comment by dolmaron** [comment]
I just wanted to open this can of worms and see if anyone has any update.  I just deployed Ago-Assistant internally and didn't find this open issue until after I had played around with it a little.  My issue is that I can't login when IWA is enabled on the portal... and then if I change it to anonymous I don't get any results in the Root folder for the portal in the display. (signed in with the default admin account)

**Comment by ecaldwell** [comment]
I haven't made any attempts yet. I don't really know where to start. Can anybody shed some light on how access works when IWA is enabled? It's different than enterprise logins right? Is there a certificate that gets passed to Portal?

@dolmaron When you signed in with the default admin account, could you modify the search dropdown to look at all content in your Portal and find things that way?

![screen shot 2015-02-03 at 10 25 38 am](https://cloud.githubusercontent.com/assets/240542/6023017/0a6fae66-ab8f-11e4-97f0-22ceb6c8b6c7.png)

**Comment by ecaldwell** [comment]
I think I have the approach now (@olearydw set me straight). There's a session cookie that Portal sets once you're authenticated. I need to basically rip out the OAuth handler in favor of a handler for that cookie. I'll work on putting up a separate branch that you can deploy with your Portal to test. Stay tuned.

**Comment by lpsnyd** [comment]
This would be a great enhancement!

**Comment by dolmaron** [comment]
@ecaldwell I would greatly appreciate that.  Let me know if you would like me to test anything in response to your updates.

**Comment by ecaldwell** [comment]
I pushed up a [new branch to test with](https://github.com/ecaldwell/ago-assistant/tree/support_IWA) on my fork. Can you download that version, change line 105 in `js/main.js` to reflect your domain and then deploy on the same domain as your Portal. Sign into your Portal, then open this app and see if it works.

**Comment by dolmaron** [comment]
Testing it now

**Comment by dolmaron** [comment]
Ok, at first it was not working, but I was able to find the issue.  It looks like there was a leftover handle in the logic of main.js on line 102 for some testing that was being done.  The value of cookie("test") was in there for the JSON.parse.  After looking at this I changed it to 

```
    // Check if the user has already authenticated with IWA.
    if (cookie("esri_auth")) {
        var esri_auth = JSON.parse(cookie("esri_auth"));
```

instead of 

```
    // Check if the user has already authenticated with IWA.
    if (cookie("esri_auth")) {
        var esri_auth = JSON.parse(cookie("testing"));
```

**Comment by ecaldwell** [comment]
Good catch. Thought I had gotten the test variable swapped out, but obviously not! Most stuff should work, but copying content may not. That may take some extra handling. Let me know what you see.

**Comment by dolmaron** [comment]
So far so good on behavior, unfortunately one of the major items I was planning on using the AGO assistant for is for moving data between two portals, one here in the US and one in the UK.  I have tested this behavior and it does appear to fail when attempting to log into the UK portal.

As a side note, how does the AGO Assistant handle moving a portal item between two portals when the service behind the portal item is coming from a federated ArcGIS Server?

**Comment by ecaldwell** [comment]
Good news, there is a much simpler approach to implementing this support. The cookie finding is unnecessary. The IWA and PKI authentication can be handled and captured with the initial call to `self` which was already implemented for URL validation. This call fires off the web authentication for IWA and PKI portals. I plan to push up the change in the next several days for you all to test.

There are several benefits to the new approach:
  * doesn't require a separate code branch
  * will allow use of the app even when the app is hosted on a different domain than the portals (including the existing [cloud hosted version](https://ago-assistant.esri.com))
  * will allow for authenticating with two different enterprise auth portals in the same session (e.g. copying from an IWA secured portal to a PKI secured portal)

**Comment by jmirmelstein** [comment]
We're having trouble making calls to the <code>self</code> resource as a result of it being secured with IWA.  When accessed directly from a browser, there is an authorization header attached to the request.  But this header is never created when the call is initiated from the AGO Assistant.  Furthermore, I see this call to the self resource in Chrome, but not IE11.

**Comment by ecaldwell** [comment]
Alright, thanks to some extreme hand holding from @rwmajor2 I pushed up a new branch that has a different (and hopefully better) approach. It's on the [develop branch in my fork](https://github.com/ecaldwell/ago-assistant/tree/develop). You can also give it a swing from the [staging site](http://s3.amazonaws.com/ago-assistant-staging/index.html). There should no longer be a need to download and host it locally, unless your portal and client browser are behind a firewall.

Let me know where it breaks.

**Comment by ecaldwell** [comment]
Here's some detail on what I'm *expecting* to happen. 

Entering the URL to a PKI or IWA secured portal should automatically kick off web tier authentication (this is due to a URL validation step that makes a call to the portal's `sharing/rest` endpoint to check that the portal can be reached at the provided URL). Once this step has completed, there is no need to enter a username or password as they are not needed. The call to `generateToken` should be allowed by web tier auth. From there, a call to `self` with the `token` gets the other required values for all future calls (mainly `username`).

**Comment by jmirmelstein** [comment]
This new branch seems to work flawlessly!  I think it's time to merge branches and buy @ecaldwell a beer or two.

**Comment by ecaldwell** [comment]
Glad it's working well for you. Let's go ahead and keep this issue open until I get the changes merged in to master.
