### ISSUE TITLE
Add support for AGO enterprise logins

### ISSUE THREAD

**Issue by oevans** [Esri/ago-assistant#55]

**Comment by torrin47** [comment]
+1

**Comment by hsimonusa** [comment]
+1

**Comment by oevans** [comment]
Copy task?

Sent from my mobile device
Owen Evans

On Jan 23, 2015, at 2:30 PM, Evan Caldwell <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #55<https://github.com/Esri/ago-assistant/issues/55> via #64<https://github.com/Esri/ago-assistant/pull/64>.

**Comment by ecaldwell** [comment]
Not for the destination yet. I've got an idea for how to enable this capability without worrying about having to add OAuth for destination logins (very tricky since OAuth is a singleton in the JS API).

**Comment by ecaldwell** [comment]
Enterprise logins for destination accounts are now supported thanks to #112.
