### ISSUE TITLE
Update Operational Layer Content

### ISSUE THREAD

**Issue by shmel** [Esri/ago-assistant#57]
In an AGO Webmap with a large number of layers, updating Field order for popups and popup content is cumbersome through the AGO interface. We have gotten around this by customizing webmaps in a WebMap JSON file. However, then we can no longer use the AGO webmap which is now out of date. 

It would be great to be able to edit the JSON manually, or be able to update the content for multiple similar layers.

**Comment by ecaldwell** [comment]
Editing JSON is now available (added in #64). Let me know if it works out for your use case.
