### ISSUE TITLE
Allow the Administrator to Administrate AGOL

### ISSUE THREAD

**Issue by KRathgeber** [Esri/ago-assistant#63]
Really have to ask why the administrator of an AGOL organization has so little ability to administrate his organization.  Being able to only see those items of which that administrator is owner of is very,very limiting in what one can do.

**Comment by ecaldwell** [comment]
I agree this is a big shortcoming of the app's current state. The good news is that I'm finalizing an update that will let you see any content you have permissions to: content you own, content shared with your org, and content shared publicly in ArcGIS Online. Your ability to work with that content will be controlled by your permissions. For example, as an admin you can update the URL's of a registered service owned by someone else in the organization.

Thanks for the feedback!

**Comment by KRathgeber** [comment]
Nice….thank you very much.  I have been waiting for that for some time.

Now if I can get them to incorporate better administrative abilities into AGOL my day would be made.  I really don’t like the “owner” concept that has been implemented.  While it is a decent item to have has part of the metadata for searching and seeing your own content, it is not convenient at all for managing a site.

Kevin Rathgeber | tel 306.975.2301
GIS Systems Analyst
CGIS, Information Technology
City of Saskatoon | 222 3rd Avenue North | Saskatoon, SK  S7K 0J5
kevin.rathgeber@saskatoon.ca<mailto:kevin.rathgeber@saskatoon.ca>
www.saskatoon.ca<http://www.saskatoon.ca>

If you receive this email in error, please do not review, distribute or copy the information.
Please contact the sender and delete the message and any attachments.

**Comment by ecaldwell** [comment]
Resolved with #64
