### ISSUE TITLE
Accessign the view item ison is showing nothing

### ISSUE THREAD

**Issue by juliagalindo** [Esri/ago-assistant#68]
Hi,

I tried to access the View item Json in the drop down menu “Iwant to” but I got this error. 

![image](https://cloud.githubusercontent.com/assets/11063803/6253326/0ba14f50-b766-11e4-94d2-d847a2a334d9.png)

Thanks,

**Comment by ecaldwell** [comment]
It looks like you're trying to access your own portal and are running into an issue with CORS. You could try [downloading](https://github.com/Esri/ago-assistant/archive/master.zip) the app and running it locally to see if that resolves your access issues.

**Comment by ecaldwell** [comment]
Hi @juliagalindo, I'm curious if last night's update resolved your issue. Can you test again and let me know if you experience any similar problems?
