### ISSUE TITLE
Issues connecting to https://devext.arcgis.com over VPN

### ISSUE THREAD

**Issue by crai3162** [Esri/ago-assistant#69]
When connecting to one of our sites on https://devext.arcgis.com, the login is successful, however there's nothing listed and no Root menu is displayed.  This seems to only happen over VPN, when I'm in the office connected to the internal network, I can connect and view Root menu and the items I own.

**Comment by ecaldwell** [comment]
Have you watched the console or network traffic for any clues to where it's failing?

**Comment by crai3162** [comment]
Nope, have not tried either of those.  I was able to narrow down the issue a little more today.  It seems to be specific to my Macbook over VPN.  When I connect to the portal on a Windows machine over VPN, it's successful.

**Comment by ecaldwell** [comment]
Closing this out as it sounds like it is unique to your environment. Let me know if you see a consistent issue with it.
