### ISSUE TITLE
Change needed for 'Help' splash screen

### ISSUE THREAD

**Issue by RachelWeeden** [Esri/ago-assistant#70]
The Help splash screen still states that hosted feature services cannot be copied; this was made possible in the Sept '14 release, correct?

**Comment by ecaldwell** [comment]
Kinda sorta. It depends on what you would consider "copying" to mean.

In its current state, you can copy a feature service item, which effectively registers an existing feature service in a new org or portal. The URL to the service does not change.

What many have asked for is the ability to deep copy a feature service which would mean spinning up a new hosted feature service at the destination (with all the schema, data, and symbology of the first).

You still have a very valid point so I think the best path forward is to *amend* the help section to clarify. Thanks for pointing this out.

**Comment by RachelWeeden** [comment]
Makes sense, thanks Evan. I agree that the ability to deep copy would be a valued enhancement!
