### ISSUE TITLE
Allow to Move items between folders

### ISSUE THREAD

**Issue by nixta** [Esri/ago-assistant#71]
Similar to Copy to My Account, but just move. The interface is so much slicker than the My Content viewer that this could really help an org that's got a bit out of control.

Er... I've got a friend who has one like that...

**Comment by nheminger** [comment]
Great idea. What would the UI look for this? Drag from the left section to the folder you want to move it to on the right?

**Comment by nixta** [comment]
Yeah, I think so.

The `Copy Content` tool might be a good starting point.

If you look at the `Copy Content` tool's right-hand side, you have to expand the folder to see its content and have a drop-zone at the top. I understand the usefulness of seeing other content in the folder, but it'd be good to just be able to drop it on the unexpanded folder. Perhaps each folder bar could have a drop zone on it too.

![2016-11-08_16-43-15](https://cloud.githubusercontent.com/assets/25374/20118609/2452319c-a5d3-11e6-92c9-be719b7ee856.png)

It might also be useful to select multiple things on the left to copy rather than doing one-by-one.

**Comment by slibby** [comment]
Going forward, AGO-Assistant will be designed and updated to primarily focus on item-level workflows that are not already available in the UI of ArcGIS Online, this is better served through a simple user workflow in the ArcGIS Online interface, which already exists.
