### ISSUE TITLE
Viewing JSON of Content Files Slow to Load

### ISSUE THREAD

**Issue by kevinsigwart** [Esri/ago-assistant#72]
When trying to view a content item that is a saved file (Service Definition, Map/Layer Packages, ...) the view JSON is slow to load on those items as if it is actually trying to download the content.  It would be great if the initiate download doesn't start till the download link is clicked.

**Comment by ecaldwell** [comment]
> ...as if it is actually trying to download the content.

That's exactly what's happening as soon as a request is made to the `/data` endpoint for file based items. Maybe I can add a timeout or abort the request.

**Comment by slibby** [comment]
This has been resolved in the change to using `ace` for JSON viewing.
