### ISSUE TITLE
Provide way to Refresh Content without logging out

### ISSUE THREAD

**Issue by kevinsigwart** [Esri/ago-assistant#73]
It would be a great enhancement to add the ability to refresh My Content to show the latest entries without having to log out and log back in again.  Once you log in, the application loads all the items.  If an Item is deleted that item is still showing up in the list and there is no way to get rid of it or refresh to show new content added without refreshing the entire site.

**Comment by ecaldwell** [comment]
The "View My Content" option in the search dropdown will reload all of your content to reflect any recent changes. I'm all ears for a more intuitive way to present this option to users.

![screen shot 2015-03-16 at 11 04 21 am](https://cloud.githubusercontent.com/assets/240542/6668914/79b0dad6-cbcc-11e4-9b47-9f27d1083033.png)
