### ISSUE TITLE
Error signing in to another organization (ArcGIS Online) to copy content

### ISSUE THREAD

**Issue by tjmichael81** [Esri/ago-assistant#77]
Error in console when attempting to sign in to another organization to copy content:

![image](https://cloud.githubusercontent.com/assets/3991055/6754237/b7564e20-cef1-11e4-920c-b92b2ea8eacb.png)

**Comment by ecaldwell** [comment]
Thanks for catching this @tjmichael81. It was a new bug I introduced with the last update. I've just pushed up a fix. Clear your cache and reload the site and let me know if you run into any other issues.

**Comment by tjmichael81** [comment]
Just tested and I was able to sign in to the second org.  Thanks @ecaldwell!!
