### ISSUE TITLE
Implement "Copy Full Account" function

### ISSUE THREAD

**Issue by oevans** [Esri/ago-assistant#8]
Would be great to have a button that migrates all content (including folders) AND group ownership (and membership, if possible) from one account to another.  This would be particularly useful when migrating from AGO accounts to enterprise login accounts (new feature in March 2013 release).

**Comment by ecaldwell** [comment]
I think this type of task is better suited for Python because of the extreme nature of what it does. As you are aware, there's [a working example](https://github.com/ecaldwell/portal-admin-examples/blob/master/migrateAccount.py) to use for this exact task.
