### ISSUE TITLE
Incorrect username passed for onsite Portal

### ISSUE THREAD

**Issue by GISSupport** [Esri/ago-assistant#80]
I login as user
Online Assistant 'correctly' identifies me as user@DOMAIN.
Portal has me stored as user@DOMAIN

When I select "view my stats" the following URL is passed:
/arcgis//sharing/rest/community/users/user?&token

It should be:
/arcgis//sharing/rest/community/users/user@DOMAIN?&token

I suspect the same issue will occur with "view my content"

Side note ... have also had issues with Collector with when DOMAIN is and isn't needed

Thanks

**Comment by ecaldwell** [comment]
I tested and it's still working ok on my end with an enterprise login. This could be a caching issue. Try clearing out you browser cache, reload, and see if it happens again.

**Comment by GISSupport** [comment]
Apologies for the delay.

I have coped the AGO Assistant to a local server as I was unable to log into my portal from https://ago-assistant.esri.com/

Any URLs for user fail.
If I retype direct into a browser with user@DOMAIN they work.

My portal is https://collector.uat.rfs.nsw.gov.au/arcgis

Thanks

**Comment by GISSupport** [comment]
The latest version has resolved this.

https://github.com/Esri/ago-assistant/releases latest version isn't the latest?
