### ISSUE TITLE
I don't see the "Secured with IWA" option when running AGO onsite

### ISSUE THREAD

**Issue by GISSupport** [Esri/ago-assistant#81]
Is this really an issue?

Thanks

**Comment by ecaldwell** [comment]
I'm not sure I understand...could you provide some more detail? Did you download the app and host it locally and that's where you're not seeing the checkbox for IWA?

**Comment by GISSupport** [comment]
Yes I am hosting the app locally.

My portal is using IWA.
When I tried to login in from https://ago-assistant.esri.com/ there was a check box option
I can login in locally if I provide my username and password though.

**Comment by ecaldwell** [comment]
Based on the other issues you're experiencing I think you may have a broken or dated version of the app. Can you try [downloading the latest version](https://github.com/Esri/ago-assistant/archive/master.zip) and test again?

**Comment by GISSupport** [comment]
Correct!

I grabbed the "latest" version from https://github.com/Esri/ago-assistant/releases and it isn't :)

**Comment by ecaldwell** [comment]
You're right, I need to start tagging and pushing all updates (no matter how minor) into the releases page.
