### ISSUE TITLE
Copying content from a 10.2.2 Portal to a 10.3 Portal fails

### ISSUE THREAD

**Issue by bstayeresri** [Esri/ago-assistant#82]
I'm trying to copy content from a 10.2.2 Portal to a 10.3 Portal. Every time I drag something over, it fails, saying, "Copying failed! 'type' and 'title' property required." This happens with ArcGIS Server map services, web maps, and external (not hosted) applications.

**Comment by ecaldwell** [comment]
Are you able to copy the source items anywhere else successfully (like ArcGIS Online)?

**Comment by bstayeresri** [comment]
Yes, I can successfully copy from the 10.2.2 Portal to ArcGIS Online. I can also successfully copy content from ArcGIS Online to the 10.3 Portal.

**Comment by ecaldwell** [comment]
Tested and it's working now. Closing this one out since we can't reproduce. Maybe the [tubes were filled](http://en.wikipedia.org/wiki/Series_of_tubes). :wink:
