### ISSUE TITLE
Scene Layers & Web Scenes

### ISSUE THREAD

**Issue by BrianRSims** [Esri/ago-assistant#83]
AGO Assistant does not seem to support Scene Layers or Web Scene items.  Is this something that can be added?

**Comment by ecaldwell** [comment]
Yes, it's a fairly easy fix. Basically, there's a whitelist of item types that can be copied. In its current state, the app can copy anything that is non-file based. I need to update the whitelist to reflect the latest set of item types as [documented here](http://resources.arcgis.com/en/help/arcgis-rest-api/index.html#//02r3000000ms000000).

Eventually, I'd like to move the whitelist to a config file, but for now you can [find it here](https://github.com/Esri/ago-assistant/blob/master/src/js/main.js#L957-L977).
