### ISSUE TITLE
Unable to update service URLs of a web map with local install of assistant

### ISSUE THREAD

**Issue by GISSupport** [Esri/ago-assistant#84]
Hi again

When I click Update nothing happens and the Chrome debugger shows:
Uncaught TypeError: Cannot read property 'replace' of undefined      main.js:675

I'm guessing it's something I have done wrong.

Thanks

**Comment by ecaldwell** [comment]
Do you get the same error when using the [hosted version](https://ago-assistant.esri.com)? Alternatively, have you tried downloading and redeploying the app internally? It sounds like something has gone wrong with your build. What function is line 675 part of? In the current version, [that's a blank line](https://github.com/Esri/ago-assistant/blob/master/src/js/main.js#L675).

**Comment by GISSupport** [comment]
Yes, now works as have downloaded the latest version.

**Comment by GISSupport** [comment]
Yes, now works as have downloaded the latest version.
