### ISSUE TITLE
The 'Access-Control-Allow-Origin' header contains multiple values for POST requests

### ISSUE THREAD

**Issue by GISSupport** [Esri/ago-assistant#86]
Similar to this, maybe?:
http://www.ngroutes.com/questions/AUuACmb5a5vEqxqlK2aP/the-access-control-allow-origin-header-contains-multiple-values-but-on.html

I get the error when I go to log into a second Portal to copy content.

**Comment by nheminger** [comment]
Is this the response header that contains multiple 'Access-Control-Allow-Origin' values? Is this response coming back from a Portal instance or ArcGIS Online? This appears to be a configuration issue with the hosting Portal instance rather than the ArcGIS Online Assistant.

**Comment by nheminger** [comment]
@GISSupport, Can you confirm what headers are being returned on the response for this one?

**Comment by GISSupport** [comment]
@nheminger Hmmm ... this has resolved itself.

A CORS issue that I'm guessing was fixed due to another internal issue.
