### ISSUE TITLE
Can't log in via enterprise login using IE 11

### ISSUE THREAD

**Issue by JeffJacobson** [Esri/ago-assistant#89]
When I attempt to log in using my enterprise credentials in IE, I am not able to do so. After the popup info closes, I am just taken back to the login screen.

Since IE is being replaced by Edge soon, I don't know if you want to bother fixing this, but it should at least be documented.

**Comment by ecaldwell** [comment]
Is this with an ArcGIS Online org or Portal? Are you still seeing the same behavior today?

**Comment by JeffJacobson** [comment]
@ecaldwell, this occurs when I try to log in with my enterprise login via ArcGIS Online (https://wsdot.maps.arcgis.com). I tried it just now and it is still happening.

It's also possible that this has something to do with how my agency has IE configured. E.g., I just found out recently that [Font Awesome] icons don't work in IE *only when I am at work*. At home they work just fine in IE. (I tried multiple computers at work, so its some agency-wide IE setting that's screwing up [Font Awesome].)
[Font Awesome]:http://fontawesome.io/

**Comment by ecaldwell** [comment]
Have you been able to test from a different browser? Which version of IE?

**Comment by JeffJacobson** [comment]
*Have you been able to test from a different browser?*
Yes, everything works fine in Chrome and Firefox. It is no problem for me to use another browser.

*Which version of IE?*
IE 11

![2015-07-16 11_32_09-about internet explorer](https://cloud.githubusercontent.com/assets/713754/8731787/705fbe9c-2bae-11e5-9dd4-d639512914ee.png)

**Comment by ecaldwell** [comment]
OK, I'm actually seeing the same thing. The funny thing is, if I refresh the page and choose enterprise login again, it immediately takes me to my content. Do you get that too?

I'll try and dig around and see if I can figure out what IE doesn't like about the callback from the Oauth handler.

**Comment by JeffJacobson** [comment]
No, the refresh trick doesn't work for me. In the dialog shown on the last screenshot, I've tried clicking both *Yes* and *No*, but neither one allows me to log in.

I took some screenshots to show exactly what I am doing when logging in.
![2015-07-16 12_44_18-sign in - internet explorer](https://cloud.githubusercontent.com/assets/713754/8733549/281c2f84-2bb9-11e5-8d24-ae94b679334e.png)
![2015-07-16 12_44_40-sign in - internet explorer](https://cloud.githubusercontent.com/assets/713754/8733562/334e5364-2bb9-11e5-8556-e786721aa8e5.png)
![2015-07-16 12_44_56-sign in to wsdot online map center - internet explorer](https://cloud.githubusercontent.com/assets/713754/8733572/3b484520-2bb9-11e5-8d74-b6d08bad5452.png)
![2015-07-16 12_45_18-windows internet explorer](https://cloud.githubusercontent.com/assets/713754/8733575/3ff672d6-2bb9-11e5-8c17-f2a1e7562f51.png)

**Comment by nheminger** [comment]
@JeffJacobson Can you open the debugging console and see if you have any errors listed when this happens?

**Comment by JeffJacobson** [comment]
No, I'm not seeing any messages in the debugging console.

**Comment by nheminger** [comment]
@JeffJacobson Okay, thanks for checking that. Does adding the ArcGIS Online Assistant site to your IE's "Trusted sites" change the behavior at all?

**Comment by ecaldwell** [comment]
@JeffJacobson It's been a while since there was any active discussion around this issue. I'm going to close this out as `not repoducible`. If the behavior described above is still happening just let me know and we'll reopen it.

**Comment by erinmeyers88** [comment]
I am getting this issue right now. Did anyone find a solution?

**Comment by slibby** [comment]
@erinmeyers88 the solution we have right now is to use another browser - I just tested it myself with IE and Enterprise logins with AGO and didn't have any issues. Are you in a position to run Fiddler while going through the login process, and look for any failed or denied requests?

**Comment by bdvogt** [comment]
I am also still having this issue.  As best as I can tell, I have isolated it to issues using Enterprise login when a pop-up is involved.  I have issues using IE11 Enterprise login at arcgis.com and also for some embedded maps.  I do not have an issue navigating directly to a web app url.  When navigating directly to a webapp, the login process takes place completely within the same window and works fine.  Whenever a popup is involved requesting the Enterprise login, it does not seem to pass back the credentials to the original page.
