### ISSUE TITLE
Show Item ID & Owner for Items in Search Results

### ISSUE THREAD

**Issue by jmirmelstein** [Esri/ago-assistant#90]
When I search my ArcGIS Online Organization for a particular web map item, I may receive multiple results...multiple users having maps with the same title.  If we want to use the 'Update the URLs of Services in a WebMap', we have no way of knowing which map is which.  Can you please include an Item ID and owner Name with each item in the search results?

**Comment by ecaldwell** [comment]
What, you don't like inspecting every item to figure all of that out?

I've tried to keep the item info as clean as possible, but I agree that more metadata needs to be exposed. I've thought about adding a little info button that would hover a popup with the extra info. Do you think that would suffice? Any suggestions?

**Comment by jmirmelstein** [comment]
The challenge is that sometimes you have the same Item duplicated in a Portal, so we want to make sure that whatever item we're updating/modifying in any way is the correct item.  

I would suggest maybe a popup when you hover over an item in the Search Results list.  For starters, I think just showing Item ID on hover would be good enough.

**Comment by GISDev01** [comment]
> What, you don't like inspecting every item to figure all of that out?

Haha, good one

I've also experienced this exact issue where the item name was the exact same in the search results, but one was owned by a 'Production' user account and the other owned by the 'Staging' user account. Would be great to have the Item ID and the Item Owner Username in an on-hover popup or another mechanism.

I will put something together soon for this one to see how it looks in practice.

**Comment by rwmajor2** [comment]
Addressed via PR #194.
