### ISSUE TITLE
Problem with updating map service urls in Story Map

### ISSUE THREAD

**Issue by richardsr-saccounty** [Esri/ago-assistant#94]
Updating the map service URL's in a Story Map application did not work. We updated all of the individual web maps and the story map is still referencing the old web map definitions. Looks like we have to recreate the story map! Darn thought this would be a helpful tool..

**Comment by ecaldwell** [comment]
Can you describe your workflow? Were you updating the URL of the Story Map itself, updating the web map IDs used in the Story Map, or updating the service URLs in the web maps?

**Comment by richardsr-saccounty** [comment]
Workflow for this was:
Creating Story Map and Web Maps in ArcGIS Personal Account
Used AGO Assistant to move content to Organizational Account
Used AGO Assistant to update the map service url’s in the Web Maps

All of the web maps were updated and but when the Story Map application when launched is still referencing the old web map definitions somehow.

We inspected the Story Map json and the web map ID’s do not match the migrated web map ID’s.

**Comment by ecaldwell** [comment]
Unfortunately, it doesn't handle updating the web maps. In the future, I may try to expand a deep copy option that automatically copies over and updates the dependencies for a given app (i.e. all of the web maps and services).

For now, your best bet is to edit the `JSON` in the data window to reflect the new webmap ids.

**Comment by richardsr-saccounty** [comment]
We also edited the web map id’s for several of the maps but this did not seem to work either. Maybe I have to close out of all of my sessions and clear cache

**Comment by oevans** [comment]
Here's a draft blog post with a procedure for copying a story map from one org to another:

https://medium.com/@OwenGeo/440586dffdf1

**Comment by ecaldwell** [comment]
Closing this out as a question that has been answered and a current known limitation. Hopefully, we can automate some of the swizzling of the webmap id in the future.
