### ISSUE TITLE
Error Running Live AGO-Assistant (NetworkError 403 on js file)

### ISSUE THREAD

**Issue by shaunnicholson** [Esri/ago-assistant#95]
AGO-Assistant doesn't start.  Firebug reports the following error:

"NetworkError: 403 Forbidden - https://ago-assistant.esri.com/js/lib/arcgis/dojo/cldr/nls/en-gb/gregorian.js"

Navigating directly to the above URL give the error:

<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>90D77FF5240197EE</RequestId><HostId>R8dNn0Spnuo3qltgKCVIhHg0VBgJTz6SSVIauG5A7nKAh7J5XFNvhWO/Iy41nYgMrQbblWdUNlc=</HostId></Error>

**Comment by ecaldwell** [comment]
Try clearing your cache and reloading. The app uses an optimized build of the JSAPI now so it may just be looking for an old file that doesn't exist. Aside from that, it could be a caching issue with one of the cloudfront distros. Let me know.

**Comment by shaunnicholson** [comment]
Hi
Cleared browser cache, I get the same error.
As in the post above using the URL https://ago-assistant.esri.com/js/lib/arcgis/dojo/cldr/nls/en-gb/gregorian.js directly in a web browser gives the same error.
Also fails from a machine which has never used AGO-Assistant before (IE11).
Thanks
Shaun

**Comment by garys-esri** [comment]
Have you tried it in Chrome? I just tried it in Internet Explorer for the first time and it doesn't work there for me either. I don't use IE unless necessary, so I didn't notice a problem until now. Try it in Chrome and tell us what you see.

**Comment by shaunnicholson** [comment]
Yes works fine in Chrome.  I normally use Firefox and get the same error there.

**Comment by ecaldwell** [comment]
Okay, so I get the same error when I switch my browser locale to english-gb (as well as many others). This leads me to believe the JS Web Optimizer is not properly bundling all of the locales supported by the JSAPI. 

I'm going to reach out to the javascript team to see about a long term solution. In the short term, I think if you switch your browser locale to english-US while using this app then things should work ok.

**Comment by ecaldwell** [comment]
Just saw your last comment verifying it works in Chrome. That's a better short term solution. :smiley:

**Comment by shaunnicholson** [comment]
Hi
For reference 'just' running Chrome is not enough as some Chrome installs default to local locales.
My Chrome worked as it just happened to be using English (United States).
If Chrome is actually set to use English (United Kingdom) (or some other locale) then it would need to be changed to English (United States) for AGO-Assistant to work (at least that's what we have found).
Thanks
Shaun
