### ISSUE TITLE
How to copy to org that uses enterprise login

### ISSUE THREAD

**Issue by JenniferKuntz** [Esri/ago-assistant#96]
I would like to copy data from an ArcGIS Online org with a standard login (for lack of a better term) to an org that uses an enterprise login. I sign in to the ago-assistant using the standard login, but after I click Copy Content I do not find a way to log in to the org with the enterprise login. Is there a trick to doing so? Is there some other way to copy from the enterprise login org to the standard login org? I can go in the opposite direction sucessfully.

**Comment by JenniferKuntz** [comment]
A workaround for this is to make a second login in the org that uses my enterprise login. I can first transfer my content to the second login and then log in to ago-assistant using that non-enterprise login. (Thanks for the tip Jeremiah)

**Comment by ecaldwell** [comment]
Glad you found a viable workaround to meet your short term needs.

This is an unfortunate limitation that I'm aware of, but have not crafted a solution for. The OAuth mechanism [is a singleton](https://developers.arcgis.com/javascript/jsapi/identitymanager-amd.html) so once you've signed in with it, I can't reuse that nice form and login without blasting the existing credentials. I think what I may try to do is capture the token from the first round, store it, delete the existing OAuth object, present it for logging in to the destination account, then put everything back where it was. If that doesn't work, the only alternative may be to rebuild the OAuth login form.

To be continued...

**Comment by nheminger** [comment]
@JenniferKuntz I am working on a fix to allow this and it looks like I should have it working soon so that I can submit it for review.

**Comment by nheminger** [comment]
I have a lot of this working, but I introduced a bug when a user tries to repeatedly log into different destination portal instances. I'm tracking this issue down and doing further testing before I can submit a PR for this one.

**Comment by nheminger** [comment]
Done! I think this PR will fix things and allow a second ArcGIS Online/enterprise login for the destination server to allow the workflow @JenniferKuntz is asking.

**Comment by JenniferKuntz** [comment]
That's great! Thanks for the fix @nheminger

**Comment by ecaldwell** [comment]
Added in #112.

**Comment by nheminger** [comment]
No prob @JenniferKuntz! It has a much better layout now thanks to @ecaldwell! Let me know if you run into any issues with it!
