### ISSUE TITLE
Authentication to Portal requiring HTTP 302 redirect with credentials causes login failure

### ISSUE THREAD

**Issue by nheminger** [Esri/ago-assistant#99]
When authenticating to a Portal instance secured with PKI the initial url validation check fails with:

![image](https://cloud.githubusercontent.com/assets/5648650/11161220/c1a4aa7a-8a44-11e5-81c1-63ad91072935.png)

The https://[portal_home]/sharing/rest?f=json request sent is returning a HTTP 302 redirect response to handle PKI authentication. Since this is not allowed with CORS, Google Chrome fails to load the response.

Clicking proceed after the validation failure results in a similar HTTP 302 on the generateToken request:

![image](https://cloud.githubusercontent.com/assets/5648650/11161228/24967370-8a45-11e5-816d-c1046533d873.png)

One potential workaround is to first authenticate to the Portal in a different tab of the same browser session first. Then authentication may work since the service has already been authenticated without needing CORS.

When trying to copy to another PKI protected Portal, make sure to similarly authenticate in another browser tab so that the copy-destination Portal also works.

**Comment by ecaldwell** [comment]
What happens if you check this box?
![screen shot 2015-11-13 at 9 55 27 pm](https://cloud.githubusercontent.com/assets/240542/11161671/474eacd2-8a51-11e5-9583-89ab3b558027.png)

**Comment by nheminger** [comment]
The above is what happens when that box is checked. The issue is that this PKI protected service as part of it's authentication workflow does a HTTP 302 redirect immediately from the original url. That redirect URL does not have CORS headers returned on the response, so Chrome doesn't follow the redirect and load it (Error "No 'Access-Control-Allow-Origin' header is present on the requested resource." is shown in the console).

I have something of a patch that fixes this. I can try and submit it after I clean it up a bit.
